# generated by scripts/gen.mjs from spec/commands.json, do not edit
"""Command methods, result types and error classes for Droidline protocol 1."""

from __future__ import annotations

from typing import Any, Callable, Dict, List, Literal, Mapping, Optional, Sequence, Tuple, Type, TypedDict, Union, cast, overload

from ._errors import DroidlineError

PROTO = 1

By = Literal["text", "textContains", "id", "desc", "descContains", "class"]
Step = Union[Sequence[Any], Mapping[str, Any]]

Node = TypedDict(
    "Node",
    {
        "text": Any,
        "id": Any,
        "desc": Any,
        "class": Any,
        "package": Any,
        "bounds": Any,
        "clickable": Any,
        "long_clickable": Any,
        "checkable": Any,
        "checked": Any,
        "enabled": Any,
        "focused": Any,
        "selected": Any,
        "scrollable": Any,
        "editable": Any,
        "password": Any,
        "children": Any,
    },
    total=False,
)
"""One element of the screen tree. Field names match the selector names."""

DeviceInfo = TypedDict(
    "DeviceInfo",
    {
        "id": Any,
        "name": Any,
        "model": Any,
        "sdk": Any,
        "online": Any,
        "route": Any,
        "agent": Any,
        "ready": Any,
        "last_seen": Any,
    },
    total=False,
)

Notification = TypedDict(
    "Notification",
    {
        "key": Any,
        "package": Any,
        "title": Any,
        "text": Any,
        "time": Any,
        "actions": Any,
    },
    total=False,
)

App = TypedDict("App", {"package": Any, "label": Any, "version": Any, "system": Any}, total=False)

DumpResult = TypedDict(
    "DumpResult",
    {
        "package": str,
        "activity": str,
        "width": int,
        "height": int,
        "tree": Node,
    },
)
ScreenshotResult = TypedDict(
    "ScreenshotResult",
    {
        "format": str,
        "width": int,
        "height": int,
        "data": str,
    },
)
CurrentResult = TypedDict("CurrentResult", {"package": str, "activity": str})
TapResult = TypedDict("TapResult", {"ms": int})
LongTapResult = TypedDict("LongTapResult", {"ms": int})
SwipeResult = TypedDict("SwipeResult", {"ms": int})
TouchResult = TypedDict("TouchResult", {"via": str, "ms": int})
LongTouchResult = TypedDict("LongTouchResult", {"via": str, "ms": int})
ScrollToResult = TypedDict("ScrollToResult", {"swipes": int})
InputResult = TypedDict("InputResult", {"via": str, "ms": int})
ClearResult = TypedDict("ClearResult", {"ms": int})
SendkeyResult = TypedDict("SendkeyResult", {"via": str})
WaitResult = TypedDict("WaitResult", {"ms": int})
WaitGoneResult = TypedDict("WaitGoneResult", {"ms": int})
WakeResult = TypedDict("WakeResult", {"screen_on": bool, "locked": bool})
BatteryResult = TypedDict("BatteryResult", {"level": int, "charging": bool, "temperature": float})
InfoResult = TypedDict(
    "InfoResult",
    {
        "model": str,
        "manufacturer": str,
        "sdk": int,
        "release": str,
        "agent": str,
        "width": int,
        "height": int,
        "ready": Dict[str, Any],
    },
)
NetworkResult = TypedDict("NetworkResult", {"type": str, "airplane": bool, "metered": bool})
LaunchResult = TypedDict("LaunchResult", {"ms": int})
KillResult = TypedDict("KillResult", {"via": str, "ms": int})
ClearDataResult = TypedDict("ClearDataResult", {"via": str, "ms": int})
DataResult = TypedDict("DataResult", {"via": str, "ms": int, "accepted": bool}, total=False)
WifiResult = TypedDict("WifiResult", {"via": str, "ms": int, "accepted": bool}, total=False)
AirplaneResult = TypedDict(
    "AirplaneResult",
    {
        "via": str,
        "ms": int,
        "accepted": bool,
    },
    total=False,
)
BatchResult = TypedDict(
    "BatchResult",
    {
        "results": List[Dict[str, Any]],
        "accepted": bool,
    },
    total=False,
)
ProxyResult = TypedDict("ProxyResult", {"active": bool, "apps": List[str]})
ProxyCheckResult = TypedDict(
    "ProxyCheckResult",
    {
        "active": bool,
        "ip": str,
        "upstream": str,
        "error": str,
    },
)
PairQrResult = TypedDict("PairQrResult", {"uri": str, "expires": int})
ServerInfoResult = TypedDict(
    "ServerInfoResult",
    {
        "version": str,
        "server": str,
        "name": str,
        "proto": int,
        "agent_port": int,
        "client_port": int,
    },
)
ChromeGoResult = TypedDict("ChromeGoResult", {"ms": int})


class NotFoundError(DroidlineError):
    """The target did not appear in time. The current package/activity is returned in screen."""

    code = "NOT_FOUND"
    http = 422
    retryable = True


class AmbiguousError(DroidlineError):
    """Several elements match. Only raised in strict mode; candidates are returned."""

    code = "AMBIGUOUS"
    http = 422
    retryable = False


class NotClickableError(DroidlineError):
    """Both the node action and the coordinate tap failed."""

    code = "NOT_CLICKABLE"
    http = 422
    retryable = True


class DroidlineTimeoutError(DroidlineError):
    """The action itself timed out. Safe to retry."""

    code = "TIMEOUT"
    http = 504
    retryable = True


class NoAccessibilityError(DroidlineError):
    """Accessibility service is off."""

    code = "NO_ACCESSIBILITY"
    http = 409
    retryable = False


class NoImeError(DroidlineError):
    """The Droidline keyboard is not selected, so key codes, text and clipboard reads are unavailable."""

    code = "NO_IME"
    http = 409
    retryable = False


class NoPermissionError(DroidlineError):
    """A permission such as VPN or notification access is missing. The permission name is returned."""

    code = "NO_PERMISSION"
    http = 409
    retryable = False


class AppNotFoundError(DroidlineError):
    """Package is not installed. Similar package names are suggested."""

    code = "APP_NOT_FOUND"
    http = 422
    retryable = False


class ActivityBlockedError(DroidlineError):
    """Tried to start a non-exported activity. Suggests launching the package default."""

    code = "ACTIVITY_BLOCKED"
    http = 422
    retryable = False


class MacroFailedError(DroidlineError):
    """A settings macro could not find its button (kill, clear_data, data, wifi, airplane). The blocked step and screen are returned."""

    code = "MACRO_FAILED"
    http = 422
    retryable = True


class ProxyFailedError(DroidlineError):
    """Upstream connection or authentication failed. reason is auth, timeout, refused or protocol."""

    code = "PROXY_FAILED"
    http = 502
    retryable = True


class UnknownCmdError(DroidlineError):
    """Command not supported. The agent version is returned."""

    code = "UNKNOWN_CMD"
    http = 404
    retryable = False


class UnsupportedError(DroidlineError):
    """The phone's Android version cannot do this without ADB or root."""

    code = "UNSUPPORTED"
    http = 422
    retryable = False


class BadArgsError(DroidlineError):
    """Missing or invalid parameters."""

    code = "BAD_ARGS"
    http = 400
    retryable = False


class DeviceNotFoundError(DroidlineError):
    """No paired device has that ID or name."""

    code = "DEVICE_NOT_FOUND"
    http = 404
    retryable = False


class DeviceOfflineError(DroidlineError):
    """The device is paired but offline. Commands wait for a reconnect before failing."""

    code = "DEVICE_OFFLINE"
    http = 503
    retryable = True


class DeviceAmbiguousError(DroidlineError):
    """No device was given and more than one is online."""

    code = "DEVICE_AMBIGUOUS"
    http = 400
    retryable = False


class AgentRestartedError(DroidlineError):
    """The phone app restarted with this command in flight. Not retried automatically to avoid running it twice."""

    code = "AGENT_RESTARTED"
    http = 503
    retryable = True


class UnauthorizedError(DroidlineError):
    """Client API token missing or wrong."""

    code = "UNAUTHORIZED"
    http = 401
    retryable = False


class PairingFailedError(DroidlineError):
    """The pairing code did not match a waiting phone."""

    code = "PAIRING_FAILED"
    http = 422
    retryable = False


class InternalError(DroidlineError):
    """Bug. Please report it with the server log."""

    code = "INTERNAL"
    http = 500
    retryable = False


ERRORS: Dict[str, Type[DroidlineError]] = {
    "NOT_FOUND": NotFoundError,
    "AMBIGUOUS": AmbiguousError,
    "NOT_CLICKABLE": NotClickableError,
    "TIMEOUT": DroidlineTimeoutError,
    "NO_ACCESSIBILITY": NoAccessibilityError,
    "NO_IME": NoImeError,
    "NO_PERMISSION": NoPermissionError,
    "APP_NOT_FOUND": AppNotFoundError,
    "ACTIVITY_BLOCKED": ActivityBlockedError,
    "MACRO_FAILED": MacroFailedError,
    "PROXY_FAILED": ProxyFailedError,
    "UNKNOWN_CMD": UnknownCmdError,
    "UNSUPPORTED": UnsupportedError,
    "BAD_ARGS": BadArgsError,
    "DEVICE_NOT_FOUND": DeviceNotFoundError,
    "DEVICE_OFFLINE": DeviceOfflineError,
    "DEVICE_AMBIGUOUS": DeviceAmbiguousError,
    "AGENT_RESTARTED": AgentRestartedError,
    "UNAUTHORIZED": UnauthorizedError,
    "PAIRING_FAILED": PairingFailedError,
    "INTERNAL": InternalError,
}


class ChromeCommands:
    """The chrome.* commands, reached as d.chrome."""

    def __init__(self, owner: DeviceCommands) -> None:
        self._owner = owner

    def go(self, url: str, new_tab: Optional[bool] = None) -> ChromeGoResult:
        """Open a URL in Chrome.

        Args:
            url: Address. https:// is added if missing.
            new_tab: Open in a new tab. Default: False.

        Raises:
            AppNotFoundError: Package is not installed. Similar package names are suggested.

        Example:
            d.chrome.go("naver.com")
        """
        return cast("ChromeGoResult", self._owner._run(
            "chrome.go",
            "fields",
            {"url": url},
            new_tab=new_tab,
        ))


class DeviceCommands:
    """Commands that run on one phone. Device mixes these in and implements _run."""

    def _run(self, cmd: str, kind: str, required: Dict[str, Any], /, **optional: Any) -> Any:
        raise NotImplementedError

    def _save_image(self, cmd: str, path: Optional[str], required: Dict[str, Any], /, **optional: Any) -> Any:
        raise NotImplementedError

    def _save_json(self, cmd: str, path: Optional[str], required: Dict[str, Any], /, **optional: Any) -> Any:
        raise NotImplementedError

    @property
    def chrome(self) -> ChromeCommands:
        return ChromeCommands(self)

    def dump(self, path: Optional[str] = None, all_windows: Optional[bool] = None) -> DumpResult:
        """Return the current screen as a node tree.

        Args:
            path: Save the tree as JSON to this local file.
            all_windows: Include system windows such as the status bar and keyboard. Default: False.

        Example:
            d.dump("screen.json")
        """
        return cast("DumpResult", self._save_json("dump", path, {}, all_windows=all_windows))

    @overload
    def screenshot(
        self,
        path: None = None,
        format: Optional[Literal["png", "jpeg"]] = None,
        quality: Optional[int] = None,
        scale: Optional[float] = None,
    ) -> bytes:
        ...

    @overload
    def screenshot(
        self,
        path: str,
        format: Optional[Literal["png", "jpeg"]] = None,
        quality: Optional[int] = None,
        scale: Optional[float] = None,
    ) -> str:
        ...

    def screenshot(
        self,
        path: Optional[str] = None,
        format: Optional[Literal["png", "jpeg"]] = None,
        quality: Optional[int] = None,
        scale: Optional[float] = None,
    ) -> Union[bytes, str]:
        """Capture the screen.

        Android 11+ uses the accessibility screenshot. Android 9-10 asks once for screen capture permission.

        Args:
            path: Save the image to this local file. The extension picks png or jpeg.
            format: Image format. Default: "jpeg".
            quality: JPEG quality 1-100. Default: 80.
            scale: Resize factor 0.1-1.0, useful on mobile data. Default: 1.

        Example:
            d.screenshot("a.png")
        """
        return cast("Union[bytes, str]", self._save_image(
            "screenshot",
            path,
            {},
            format=format,
            quality=quality,
            scale=scale,
        ))

    def current(self) -> CurrentResult:
        """Foreground package and activity.

        Example:
            d.current()
        """
        return cast("CurrentResult", self._run("current", "fields", {}))

    def tap(self, x: int, y: int) -> TapResult:
        """Tap a screen coordinate.

        Args:
            x: X in screen pixels.
            y: Y in screen pixels.

        Example:
            d.tap(540, 1200)
        """
        return cast("TapResult", self._run("tap", "fields", {"x": x, "y": y}))

    def long_tap(self, x: int, y: int, ms: Optional[int] = None) -> LongTapResult:
        """Press and hold a coordinate.

        Args:
            x: X in screen pixels.
            y: Y in screen pixels.
            ms: Hold time in milliseconds. Default: 800.

        Example:
            d.long_tap(540, 1200, 800)
        """
        return cast("LongTapResult", self._run("long_tap", "fields", {"x": x, "y": y}, ms=ms))

    def swipe(
        self,
        x1: Union[int, str],
        y1: Optional[int] = None,
        x2: Optional[int] = None,
        y2: Optional[int] = None,
        ms: Optional[int] = None,
    ) -> SwipeResult:
        """Swipe between two points, or in a direction.

        Args:
            x1: Start X, or a direction: up, down, left, right.
            y1: Start Y.
            x2: End X.
            y2: End Y.
            ms: Duration in milliseconds. Default: 300.

        Example:
            d.swipe(540, 1600, 540, 400, 300)
        """
        return cast("SwipeResult", self._run(
            "swipe",
            "fields",
            {"x1": x1},
            y1=y1,
            x2=x2,
            y2=y2,
            ms=ms,
        ))

    def touch(
        self,
        by: By,
        value: str,
        nth: Optional[int] = None,
        timeout: Optional[float] = None,
    ) -> TouchResult:
        """Wait for an element and tap it.

        If the node refuses the click, the center of its bounds is tapped instead. via tells which path worked: node, parent or gesture.

        Args:
            by: Which dump field to match: text, textContains, id, desc, descContains, class.
            value: The value to match.
            nth: Index when several elements match, starting at 0. Default: 0.
            timeout: Seconds to wait for the target to appear. Default: 10.

        Raises:
            NotFoundError: The target did not appear in time. The current package/activity is returned in screen.
            NotClickableError: Both the node action and the coordinate tap failed.
            NoAccessibilityError: Accessibility service is off.

        Example:
            d.touch("id", "com.kakao.talk:id/login")
        """
        return cast("TouchResult", self._run(
            "touch",
            "fields",
            {"by": by, "value": value},
            nth=nth,
            timeout=timeout,
        ))

    def touchById(
        self,
        value: str,
        nth: Optional[int] = None,
        timeout: Optional[float] = None,
    ) -> TouchResult:
        """Wait for an element and tap it. Shorthand for touch("id", value).

        If the node refuses the click, the center of its bounds is tapped instead. via tells which path worked: node, parent or gesture.

        Args:
            value: The value to match.
            nth: Index when several elements match, starting at 0. Default: 0.
            timeout: Seconds to wait for the target to appear. Default: 10.

        Raises:
            NotFoundError: The target did not appear in time. The current package/activity is returned in screen.
            NotClickableError: Both the node action and the coordinate tap failed.
            NoAccessibilityError: Accessibility service is off.
        """
        return cast("TouchResult", self._run(
            "touchById",
            "fields",
            {"value": value},
            nth=nth,
            timeout=timeout,
        ))

    def touchByText(
        self,
        value: str,
        nth: Optional[int] = None,
        timeout: Optional[float] = None,
    ) -> TouchResult:
        """Wait for an element and tap it. Shorthand for touch("text", value).

        If the node refuses the click, the center of its bounds is tapped instead. via tells which path worked: node, parent or gesture.

        Args:
            value: The value to match.
            nth: Index when several elements match, starting at 0. Default: 0.
            timeout: Seconds to wait for the target to appear. Default: 10.

        Raises:
            NotFoundError: The target did not appear in time. The current package/activity is returned in screen.
            NotClickableError: Both the node action and the coordinate tap failed.
            NoAccessibilityError: Accessibility service is off.
        """
        return cast("TouchResult", self._run(
            "touchByText",
            "fields",
            {"value": value},
            nth=nth,
            timeout=timeout,
        ))

    def touchByDesc(
        self,
        value: str,
        nth: Optional[int] = None,
        timeout: Optional[float] = None,
    ) -> TouchResult:
        """Wait for an element and tap it. Shorthand for touch("desc", value).

        If the node refuses the click, the center of its bounds is tapped instead. via tells which path worked: node, parent or gesture.

        Args:
            value: The value to match.
            nth: Index when several elements match, starting at 0. Default: 0.
            timeout: Seconds to wait for the target to appear. Default: 10.

        Raises:
            NotFoundError: The target did not appear in time. The current package/activity is returned in screen.
            NotClickableError: Both the node action and the coordinate tap failed.
            NoAccessibilityError: Accessibility service is off.
        """
        return cast("TouchResult", self._run(
            "touchByDesc",
            "fields",
            {"value": value},
            nth=nth,
            timeout=timeout,
        ))

    def long_touch(
        self,
        by: By,
        value: str,
        ms: Optional[int] = None,
        nth: Optional[int] = None,
        timeout: Optional[float] = None,
    ) -> LongTouchResult:
        """Wait for an element and press and hold it.

        Args:
            by: Which dump field to match: text, textContains, id, desc, descContains, class.
            value: The value to match.
            ms: Hold time in milliseconds. Default: 800.
            nth: Index when several elements match, starting at 0. Default: 0.
            timeout: Seconds to wait for the target to appear. Default: 10.

        Example:
            d.long_touch("text", "메시지")
        """
        return cast("LongTouchResult", self._run(
            "long_touch",
            "fields",
            {"by": by, "value": value},
            ms=ms,
            nth=nth,
            timeout=timeout,
        ))

    def scroll_to(
        self,
        by: By,
        value: str,
        direction: Optional[Literal["down", "up", "left", "right"]] = None,
        max_swipes: Optional[int] = None,
        nth: Optional[int] = None,
    ) -> ScrollToResult:
        """Scroll until an element is visible.

        Args:
            by: Which dump field to match: text, textContains, id, desc, descContains, class.
            value: The value to match.
            direction: Direction the content moves toward. Default: "down".
            max_swipes: Give up after this many swipes. Default: 20.
            nth: Index when several elements match, starting at 0. Default: 0.

        Example:
            d.scroll_to("text", "설정")
        """
        return cast("ScrollToResult", self._run(
            "scroll_to",
            "fields",
            {"by": by, "value": value},
            direction=direction,
            max_swipes=max_swipes,
            nth=nth,
        ))

    def input(
        self,
        by: By,
        value: str,
        text: str,
        append: Optional[bool] = None,
        nth: Optional[int] = None,
        timeout: Optional[float] = None,
    ) -> InputResult:
        """Wait for a field and set its text.

        Uses the accessibility set-text action. Fields that ignore it fall back to the Droidline keyboard when it is selected.

        Args:
            by: Which dump field to match: text, textContains, id, desc, descContains, class.
            value: The value to match.
            text: Text to enter.
            append: Keep existing text and add to the end. Default: False.
            nth: Index when several elements match, starting at 0. Default: 0.
            timeout: Seconds to wait for the target to appear. Default: 10.

        Example:
            d.input("id", "com.kakao.talk:id/email", "knife")
        """
        return cast("InputResult", self._run(
            "input",
            "fields",
            {"by": by, "value": value, "text": text},
            append=append,
            nth=nth,
            timeout=timeout,
        ))

    def clear(
        self,
        by: By,
        value: str,
        nth: Optional[int] = None,
        timeout: Optional[float] = None,
    ) -> ClearResult:
        """Empty a text field.

        Args:
            by: Which dump field to match: text, textContains, id, desc, descContains, class.
            value: The value to match.
            nth: Index when several elements match, starting at 0. Default: 0.
            timeout: Seconds to wait for the target to appear. Default: 10.

        Example:
            d.clear("id", "com.kakao.talk:id/email")
        """
        return cast("ClearResult", self._run(
            "clear",
            "fields",
            {"by": by, "value": value},
            nth=nth,
            timeout=timeout,
        ))

    def sendkey(
        self,
        key: Optional[Union[str, int]] = None,
        text: Optional[str] = None,
    ) -> SendkeyResult:
        """Send a key name, a key code, or text.

        back, home, recents, notifications, quick_settings and lock use accessibility global actions. Other keys and text go through the Droidline keyboard to the focused field.

        Args:
            key: Key name (enter, tab, del, space, escape, up, down, left, right, back, home...), Android key code, or text to type.
            text: Type this text literally, even if it equals a key name.

        Raises:
            NoImeError: The Droidline keyboard is not selected, so key codes, text and clipboard reads are unavailable.
            BadArgsError: Missing or invalid parameters.

        Example:
            d.sendkey("enter")
        """
        return cast("SendkeyResult", self._run("sendkey", "fields", {}, key=key, text=text))

    def exists(self, by: By, value: str, nth: Optional[int] = None) -> bool:
        """Whether an element is on screen right now. Never waits.

        Args:
            by: Which dump field to match: text, textContains, id, desc, descContains, class.
            value: The value to match.
            nth: Index when several elements match, starting at 0. Default: 0.

        Example:
            d.exists("text", "광고 닫기")
        """
        return cast("bool", self._run("exists", "value", {"by": by, "value": value}, nth=nth))

    def wait(
        self,
        by: By,
        value: str,
        timeout: Optional[float] = None,
        nth: Optional[int] = None,
    ) -> WaitResult:
        """Wait until an element appears.

        Args:
            by: Which dump field to match: text, textContains, id, desc, descContains, class.
            value: The value to match.
            timeout: Seconds to wait for the target to appear. Default: 10.
            nth: Index when several elements match, starting at 0. Default: 0.

        Raises:
            NotFoundError: The target did not appear in time. The current package/activity is returned in screen.

        Example:
            d.wait("text", "완료", 30)
        """
        return cast("WaitResult", self._run(
            "wait",
            "fields",
            {"by": by, "value": value},
            timeout=timeout,
            nth=nth,
        ))

    def wait_gone(self, by: By, value: str, timeout: Optional[float] = None) -> WaitGoneResult:
        """Wait until an element disappears.

        Args:
            by: Which dump field to match: text, textContains, id, desc, descContains, class.
            value: The value to match.
            timeout: Seconds to wait for the target to appear. Default: 10.

        Raises:
            DroidlineTimeoutError: The action itself timed out. Safe to retry.

        Example:
            d.wait_gone("text", "로딩 중")
        """
        return cast("WaitGoneResult", self._run(
            "wait_gone",
            "fields",
            {"by": by, "value": value},
            timeout=timeout,
        ))

    def get_text(self, by: By, value: str, nth: Optional[int] = None) -> str:
        """Text of an element, or an empty string.

        Args:
            by: Which dump field to match: text, textContains, id, desc, descContains, class.
            value: The value to match.
            nth: Index when several elements match, starting at 0. Default: 0.

        Example:
            d.get_text("id", "com.example:id/balance")
        """
        return cast("str", self._run("get_text", "value", {"by": by, "value": value}, nth=nth))

    def checked(self, by: By, value: str, nth: Optional[int] = None) -> bool:
        """true if a switch or checkbox is on.

        Args:
            by: Which dump field to match: text, textContains, id, desc, descContains, class.
            value: The value to match.
            nth: Index when several elements match, starting at 0. Default: 0.

        Example:
            d.checked("id", "com.kakao.talk:id/auto_login")
        """
        return cast("bool", self._run("checked", "value", {"by": by, "value": value}, nth=nth))

    def enabled(self, by: By, value: str, nth: Optional[int] = None) -> bool:
        """true if the element can be pressed.

        Args:
            by: Which dump field to match: text, textContains, id, desc, descContains, class.
            value: The value to match.
            nth: Index when several elements match, starting at 0. Default: 0.

        Example:
            d.enabled("text", "다음")
        """
        return cast("bool", self._run("enabled", "value", {"by": by, "value": value}, nth=nth))

    def selected(self, by: By, value: str, nth: Optional[int] = None) -> bool:
        """true if a tab or item is selected.

        Args:
            by: Which dump field to match: text, textContains, id, desc, descContains, class.
            value: The value to match.
            nth: Index when several elements match, starting at 0. Default: 0.

        Example:
            d.selected("text", "채팅")
        """
        return cast("bool", self._run("selected", "value", {"by": by, "value": value}, nth=nth))

    def count(self, by: By, value: str) -> int:
        """Number of matching elements.

        Args:
            by: Which dump field to match: text, textContains, id, desc, descContains, class.
            value: The value to match.

        Example:
            d.count("class", "android.widget.CheckBox")
        """
        return cast("int", self._run("count", "value", {"by": by, "value": value}))

    def which(self, candidates: Sequence[Tuple[By, str]], timeout: Optional[float] = None) -> int:
        """Index of the first candidate to appear, or -1.

        Args:
            candidates: List of [by, value] pairs.
            timeout: Seconds to wait for any candidate. Default: 10.

        Example:
            d.which([("text", "로그인"), ("text", "홈")], timeout=10)
        """
        return cast("int", self._run(
            "which",
            "value",
            {"candidates": candidates},
            timeout=timeout,
        ))

    def in_app(self, package: str) -> bool:
        """true if that app is in the foreground.

        Args:
            package: Package name, for example com.android.chrome.

        Example:
            d.in_app("com.kakao.talk")
        """
        return cast("bool", self._run("in_app", "value", {"package": package}))

    def keyboard_shown(self) -> bool:
        """true if a soft keyboard is showing.

        Example:
            d.keyboard_shown()
        """
        return cast("bool", self._run("keyboard_shown", "value", {}))

    def last_toast(self, max_age: Optional[float] = None) -> str:
        """Text of the most recent toast, or an empty string.

        Args:
            max_age: Ignore toasts older than this many seconds. Default: 30.

        Example:
            d.last_toast()
        """
        return cast("str", self._run("last_toast", "value", {}, max_age=max_age))

    def color(self, x: int, y: int) -> str:
        """Pixel color at a coordinate as #RRGGBB.

        For screens without accessibility nodes, such as games.

        Args:
            x: X in screen pixels.
            y: Y in screen pixels.

        Example:
            d.color(540, 1200)
        """
        return cast("str", self._run("color", "value", {"x": x, "y": y}))

    def screen_on(self) -> bool:
        """true if the screen is on.

        Example:
            d.screen_on()
        """
        return cast("bool", self._run("screen_on", "value", {}))

    def locked(self) -> bool:
        """true if the lock screen is showing.

        Example:
            d.locked()
        """
        return cast("bool", self._run("locked", "value", {}))

    def wake(self) -> WakeResult:
        """Turn the screen on and dismiss a lock screen that has no PIN.

        Gestures fail while the screen is off. A PIN, pattern or password lock cannot be dismissed without the user.

        Example:
            d.wake()
        """
        return cast("WakeResult", self._run("wake", "fields", {}))

    def lock(self) -> None:
        """Turn the screen off and lock.

        Example:
            d.lock()
        """
        self._run("lock", "none", {})

    def battery(self) -> BatteryResult:
        """Battery level and charging state.

        Example:
            d.battery()["level"] < 20
        """
        return cast("BatteryResult", self._run("battery", "fields", {}))

    def orientation(self) -> str:
        """portrait or landscape.

        Example:
            d.orientation() == "landscape"
        """
        return cast("str", self._run("orientation", "value", {}))

    def info(self) -> InfoResult:
        """Model, Android version, screen size and permission readiness.

        Example:
            d.info()
        """
        return cast("InfoResult", self._run("info", "fields", {}))

    def network(self) -> NetworkResult:
        """Connection type (wifi, mobile, none) and airplane mode.

        Example:
            d.network()["type"] == "wifi"
        """
        return cast("NetworkResult", self._run("network", "fields", {}))

    def launch(self, package: str, activity: Optional[str] = None) -> LaunchResult:
        """Start an app, optionally at a specific activity.

        Args:
            package: Package name, for example com.android.chrome.
            activity: Activity name, either full or starting with a dot.

        Raises:
            AppNotFoundError: Package is not installed. Similar package names are suggested.
            ActivityBlockedError: Tried to start a non-exported activity. Suggests launching the package default.

        Example:
            d.launch("com.kakao.talk")
        """
        return cast("LaunchResult", self._run(
            "launch",
            "fields",
            {"package": package},
            activity=activity,
        ))

    def open_url(self, url: str, package: Optional[str] = None) -> None:
        """Open a URL or deep link.

        Args:
            url: http(s) URL or app deep link.
            package: Open with this app only.

        Example:
            d.open_url("myapp://orders/42")
        """
        self._run("open_url", "none", {"url": url}, package=package)

    def kill(self, package: str) -> KillResult:
        """Force stop an app.

        Runs a settings macro: App info, Force stop, OK. Takes a few seconds.

        Args:
            package: Package name, for example com.android.chrome.

        Raises:
            AppNotFoundError: Package is not installed. Similar package names are suggested.
            MacroFailedError: A settings macro could not find its button (kill, clear_data, data, wifi, airplane). The blocked step and screen are returned.

        Example:
            d.kill("com.kakao.talk")
        """
        return cast("KillResult", self._run("kill", "fields", {"package": package}))

    def clear_data(self, package: str) -> ClearDataResult:
        """Clear an app's data.

        Runs a settings macro: App info, Storage, Clear data, OK.

        Args:
            package: Package name, for example com.android.chrome.

        Raises:
            AppNotFoundError: Package is not installed. Similar package names are suggested.
            MacroFailedError: A settings macro could not find its button (kill, clear_data, data, wifi, airplane). The blocked step and screen are returned.

        Example:
            d.clear_data("com.android.chrome")
        """
        return cast("ClearDataResult", self._run("clear_data", "fields", {"package": package}))

    def apps(self, system: Optional[bool] = None) -> List[App]:
        """Installed packages.

        Args:
            system: Include system packages. Default: False.

        Example:
            d.apps()
        """
        return cast("List[App]", self._run("apps", "value", {}, system=system))

    def installed(self, package: str) -> str:
        """Version name if installed, empty string if not.

        Args:
            package: Package name, for example com.android.chrome.

        Example:
            d.installed("com.kakao.talk")
        """
        return cast("str", self._run("installed", "value", {"package": package}))

    def back(self) -> None:
        """Back.

        Example:
            d.back()
        """
        self._run("back", "none", {})

    def home(self) -> None:
        """Home screen.

        Example:
            d.home()
        """
        self._run("home", "none", {})

    def recents(self) -> None:
        """Recent apps.

        Example:
            d.recents()
        """
        self._run("recents", "none", {})

    def open_notifications(self) -> None:
        """Pull down the notification shade.

        Example:
            d.open_notifications()
        """
        self._run("open_notifications", "none", {})

    def quick_settings(self) -> None:
        """Open quick settings.

        Example:
            d.quick_settings()
        """
        self._run("quick_settings", "none", {})

    def data(self, on: bool, *, wait: Optional[bool] = None) -> DataResult:
        """Turn mobile data on or off.

        Args:
            on: true to turn on, false to turn off.
            wait: Block until the phone is back and return the final result. Without it, data(False) returns {"accepted": True} as soon as the phone accepts, and the final result arrives later as a "result" event.

        Raises:
            MacroFailedError: A settings macro could not find its button (kill, clear_data, data, wifi, airplane). The blocked step and screen are returned.

        Example:
            d.data(False)
        """
        return cast("DataResult", self._run("data", "fields", {"on": on}, wait=wait))

    def wifi(self, on: bool, *, wait: Optional[bool] = None) -> WifiResult:
        """Turn Wi-Fi on or off.

        Args:
            on: true to turn on, false to turn off.
            wait: Block until the phone is back and return the final result. Without it, wifi(False) returns {"accepted": True} as soon as the phone accepts, and the final result arrives later as a "result" event.

        Raises:
            MacroFailedError: A settings macro could not find its button (kill, clear_data, data, wifi, airplane). The blocked step and screen are returned.

        Example:
            d.wifi(False)
        """
        return cast("WifiResult", self._run("wifi", "fields", {"on": on}, wait=wait))

    def airplane(self, on: bool, *, wait: Optional[bool] = None) -> AirplaneResult:
        """Turn airplane mode on or off.

        To renew the IP, put on and off in one batch so the phone runs both while offline.

        Args:
            on: true to turn on, false to turn off.
            wait: Block until the phone is back and return the final result. Without it, airplane(True) returns {"accepted": True} as soon as the phone accepts, and the final result arrives later as a "result" event.

        Raises:
            MacroFailedError: A settings macro could not find its button (kill, clear_data, data, wifi, airplane). The blocked step and screen are returned.

        Example:
            d.airplane(True)
        """
        return cast("AirplaneResult", self._run("airplane", "fields", {"on": on}, wait=wait))

    def clipboard(self, text: Optional[str] = None) -> str:
        """Write the clipboard, or read it when called without text.

        Reading on Android 10+ needs the Droidline keyboard to be the current input method.

        Args:
            text: Text to copy. Omit to read.

        Raises:
            NoImeError: The Droidline keyboard is not selected, so key codes, text and clipboard reads are unavailable.

        Example:
            d.clipboard("복사할 글")
        """
        return cast("str", self._run("clipboard", "value", {}, text=text))

    def batch(
        self,
        steps: Sequence[Step],
        stop_on_error: Optional[bool] = None,
        *,
        wait: Optional[bool] = None,
    ) -> BatchResult:
        """Run several commands on the phone in one go, even while it is offline.

        Steps are [cmd, args...] lists or {cmd, ...} objects. The step sleep(ms) only exists inside batch. If a step cuts the network, the call returns accepted and the result arrives after reconnect.

        Args:
            steps: Commands to run in order.
            stop_on_error: Stop at the first failing step. Default: True.
            wait: Block until the phone is back and return the final result. Without it, a batch with a step that cuts the network returns {"accepted": True} as soon as the phone accepts, and the final result arrives later as a "result" event.

        Example:
            d.batch([("airplane", True), ("sleep", 3000), ("airplane", False)])
        """
        return cast("BatchResult", self._run(
            "batch",
            "fields",
            {"steps": steps},
            stop_on_error=stop_on_error,
            wait=wait,
        ))

    def proxy(
        self,
        url: Optional[str],
        app: Optional[Union[str, Sequence[str]]] = None,
    ) -> ProxyResult:
        """Route chosen apps through an upstream proxy with a per-app VPN.

        Supports http:// (CONNECT) and socks5:// with user:pass. Pass null or "off" to stop. One upstream at a time. Apps that ignore the proxy setting lose network access instead of leaking.

        Args:
            url: socks5://user:pass@host:port, http://host:port, a saved profile like @kr1, or off.
            app: Package or packages to route.

        Raises:
            NoPermissionError: A permission such as VPN or notification access is missing. The permission name is returned.
            ProxyFailedError: Upstream connection or authentication failed. reason is auth, timeout, refused or protocol.
            UnsupportedError: The phone's Android version cannot do this without ADB or root.

        Example:
            d.proxy("socks5://user:pass@1.2.3.4:1080", app="com.android.chrome")
        """
        return cast("ProxyResult", self._run("proxy", "fields", {"url": url}, app=app))

    def proxy_check(self, app: Optional[str] = None) -> ProxyCheckResult:
        """Per-app proxy state and the IP the outside world sees.

        Args:
            app: Package to check.

        Example:
            d.proxy_check("com.android.chrome")["ip"]
        """
        return cast("ProxyCheckResult", self._run("proxy_check", "fields", {}, app=app))

    def notifications(self, package: Optional[str] = None) -> List[Notification]:
        """Notifications currently showing.

        Args:
            package: Only this app.

        Example:
            d.notifications()
        """
        return cast("List[Notification]", self._run("notifications", "value", {}, package=package))

    def has_notification(
        self,
        by: Literal["text", "textContains", "title", "package"],
        value: str,
    ) -> bool:
        """true if a showing notification matches.

        Args:
            by: text and textContains look at both title and text.
            value: The value to match.

        Example:
            d.has_notification("textContains", "배송")
        """
        return cast("bool", self._run("has_notification", "value", {"by": by, "value": value}))

    def wait_notification(
        self,
        by: Literal["text", "textContains", "title", "package"],
        value: str,
        timeout: Optional[float] = None,
        package: Optional[str] = None,
    ) -> Notification:
        """Wait for a matching notification and return it.

        Handled by the PC server, so it does not block other commands to the phone. On Android 15+ the OS hides one-time codes from apps: you get the notification but the code is masked.

        Args:
            by: text and textContains look at both title and text.
            value: The value to match.
            timeout: Seconds to wait. Default: 60.
            package: Only from this app.

        Raises:
            DroidlineTimeoutError: The action itself timed out. Safe to retry.

        Example:
            d.wait_notification("textContains", "인증번호", 60)
        """
        return cast("Notification", self._run(
            "wait_notification",
            "value",
            {"by": by, "value": value},
            timeout=timeout,
            package=package,
        ))

    def notification_reply(self, key: str, text: str) -> None:
        """Reply inline to a notification that has a reply action.

        Args:
            key: Notification key from notifications() or a notification event.
            text: Reply text.

        Example:
            d.notification_reply(key, "확인했습니다")
        """
        self._run("notification_reply", "none", {"key": key, "text": text})

    def notification_click(self, key: str) -> None:
        """Open a notification.

        Args:
            key: Notification key from notifications() or a notification event.

        Example:
            d.notification_click(key)
        """
        self._run("notification_click", "none", {"key": key})

    def notification_dismiss(self, key: str) -> None:
        """Dismiss a notification.

        Args:
            key: Notification key from notifications() or a notification event.

        Example:
            d.notification_dismiss(key)
        """
        self._run("notification_dismiss", "none", {"key": key})

    def notify_filter(self, packages: Optional[Sequence[str]] = None) -> List[str]:
        """Choose which apps' notifications are sent to the PC. Default is none.

        Args:
            packages: Allowed packages. Omit to read the current list.

        Example:
            d.notify_filter(["com.kakao.talk"])
        """
        return cast("List[str]", self._run("notify_filter", "value", {}, packages=packages))


class ClientCommands:
    """Commands the PC server answers itself. Droidline mixes these in and implements _run."""

    def _run(self, cmd: str, kind: str, required: Dict[str, Any], /, **optional: Any) -> Any:
        raise NotImplementedError

    def wait_notification(
        self,
        by: Literal["text", "textContains", "title", "package"],
        value: str,
        timeout: Optional[float] = None,
        package: Optional[str] = None,
    ) -> Notification:
        """Wait for a matching notification and return it.

        Handled by the PC server, so it does not block other commands to the phone. On Android 15+ the OS hides one-time codes from apps: you get the notification but the code is masked.

        Args:
            by: text and textContains look at both title and text.
            value: The value to match.
            timeout: Seconds to wait. Default: 60.
            package: Only from this app.

        Raises:
            DroidlineTimeoutError: The action itself timed out. Safe to retry.

        Example:
            client.wait_notification("textContains", "인증번호", 60)
        """
        return cast("Notification", self._run(
            "wait_notification",
            "value",
            {"by": by, "value": value},
            timeout=timeout,
            package=package,
        ))

    def devices(self) -> List[DeviceInfo]:
        """Paired devices with online state and route.

        Example:
            client.devices()
        """
        return cast("List[DeviceInfo]", self._run("devices", "value", {}))

    def pair(self, code: str, name: Optional[str] = None) -> DeviceInfo:
        """Approve the phone that shows this 6-digit code.

        Args:
            code: Code shown on the phone.
            name: Name to give the device.

        Raises:
            PairingFailedError: The pairing code did not match a waiting phone.

        Example:
            client.pair("482913", name="shelf-01")
        """
        return cast("DeviceInfo", self._run("pair", "value", {"code": code}, name=name))

    def pair_qr(self, name: Optional[str] = None) -> PairQrResult:
        """Create a one-time pairing QR code valid for 10 minutes.

        Args:
            name: Name to give the device.

        Example:
            client.pair_qr()
        """
        return cast("PairQrResult", self._run("pair_qr", "fields", {}, name=name))

    def rename(self, device: str, name: str) -> DeviceInfo:
        """Give a device a name.

        Args:
            device: Device ID or name.
            name: New name.

        Example:
            client.rename("a1b2c3d4", "shelf-01")
        """
        return cast("DeviceInfo", self._run("rename", "value", {"device": device, "name": name}))

    def revoke(self, device: str) -> None:
        """Unpair a device. It must pair again to connect.

        Args:
            device: Device ID or name.

        Example:
            client.revoke("shelf-01")
        """
        self._run("revoke", "none", {"device": device})

    def subscribe(self, events: Sequence[str], device: Optional[str] = None) -> None:
        """Receive events on this connection.

        Args:
            events: Any of notification, screen, toast, device, result.
            device: Only from this device. Omit for all.

        Example:
            client.subscribe(["notification"])
        """
        self._run("subscribe", "none", {"events": events}, device=device)

    def server_info(self) -> ServerInfoResult:
        """Server version, ports and listening addresses.

        Example:
            client.server_info()
        """
        return cast("ServerInfoResult", self._run("server_info", "fields", {}))

    def auth(self, token: str) -> None:
        """Authenticate this client connection with a token.

        Args:
            token: Client token from droidline token.

        Example:
            client.auth("…")
        """
        self._run("auth", "none", {"token": token})


__all__ = [
    "PROTO",
    "By",
    "Step",
    "Node",
    "DeviceInfo",
    "Notification",
    "App",
    "DumpResult",
    "ScreenshotResult",
    "CurrentResult",
    "TapResult",
    "LongTapResult",
    "SwipeResult",
    "TouchResult",
    "LongTouchResult",
    "ScrollToResult",
    "InputResult",
    "ClearResult",
    "SendkeyResult",
    "WaitResult",
    "WaitGoneResult",
    "WakeResult",
    "BatteryResult",
    "InfoResult",
    "NetworkResult",
    "LaunchResult",
    "KillResult",
    "ClearDataResult",
    "DataResult",
    "WifiResult",
    "AirplaneResult",
    "BatchResult",
    "ProxyResult",
    "ProxyCheckResult",
    "PairQrResult",
    "ServerInfoResult",
    "ChromeGoResult",
    "NotFoundError",
    "AmbiguousError",
    "NotClickableError",
    "DroidlineTimeoutError",
    "NoAccessibilityError",
    "NoImeError",
    "NoPermissionError",
    "AppNotFoundError",
    "ActivityBlockedError",
    "MacroFailedError",
    "ProxyFailedError",
    "UnknownCmdError",
    "UnsupportedError",
    "BadArgsError",
    "DeviceNotFoundError",
    "DeviceOfflineError",
    "DeviceAmbiguousError",
    "AgentRestartedError",
    "UnauthorizedError",
    "PairingFailedError",
    "InternalError",
    "ERRORS",
    "ChromeCommands",
    "DeviceCommands",
    "ClientCommands",
]
