#!/usr/bin/env node
// Generates the SDK command layer from spec/commands.json.
//   node scripts/gen.mjs           write sdk/python/src/droidline/_generated.py, sdk/node/src/generated.ts
//                                  and sdk/dotnet/src/Droidline/Generated.cs
//   node scripts/gen.mjs --check   exit 1 if any of them is out of date
// Zero dependencies, Node >= 18.
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, relative } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const SPEC_PATH = join(ROOT, "spec", "commands.json");
const OUT_PY = join(ROOT, "sdk", "python", "src", "droidline", "_generated.py");
const OUT_TS = join(ROOT, "sdk", "node", "src", "generated.ts");
const OUT_CS = join(ROOT, "sdk", "dotnet", "src", "Droidline", "Generated.cs");
const HEADER = "generated by scripts/gen.mjs from spec/commands.json, do not edit";

const SCOPES = new Set(["device", "server", "client"]);
const KINDS = new Set(["value", "fields", "none"]);
const SAVE_MODES = new Set(["image", "json"]);
const BASE_TYPES = new Set([
  "string", "int", "number", "bool", "null", "base64", "object", "function",
  "selector", "selector_pair", "step", "image",
]);

// Handwritten members of each SDK class; a generated method with one of these names would shadow them.
const RESERVED = {
  device: ["call", "close", "client", "device", "on_notification", "onNotification"],
  client: [
    "call", "close", "device", "host", "port", "lease", "release", "on", "off", "once", "emit", "addListener",
    "removeListener", "removeAllListeners", "listeners", "rawListeners", "listenerCount",
    "eventNames", "prependListener", "prependOnceListener", "setMaxListeners", "getMaxListeners",
  ],
};
const HANDWRITTEN_CLASSES = new Set(["Device", "Droidline"]);

const PY_KEYWORDS = new Set([
  "False", "None", "True", "and", "as", "assert", "async", "await", "break", "class", "continue",
  "def", "del", "elif", "else", "except", "finally", "for", "from", "global", "if", "import", "in",
  "is", "lambda", "nonlocal", "not", "or", "pass", "raise", "return", "try", "while", "with",
  "yield", "self",
]);
const PY_BUILTIN_EXCEPTIONS = new Set([
  "ArithmeticError", "AssertionError", "AttributeError", "BlockingIOError", "BrokenPipeError",
  "BufferError", "ChildProcessError", "ConnectionAbortedError", "ConnectionError",
  "ConnectionRefusedError", "ConnectionResetError", "EOFError", "EnvironmentError",
  "FileExistsError", "FileNotFoundError", "FloatingPointError", "IOError", "ImportError",
  "IndentationError", "IndexError", "InterruptedError", "IsADirectoryError", "KeyError",
  "LookupError", "MemoryError", "ModuleNotFoundError", "NameError", "NotADirectoryError",
  "NotImplementedError", "OSError", "OverflowError", "PermissionError", "ProcessLookupError",
  "RecursionError", "ReferenceError", "RuntimeError", "SyntaxError", "SystemError", "TabError",
  "TimeoutError", "TypeError", "UnboundLocalError", "UnicodeError", "ValueError",
  "ZeroDivisionError",
]);
const JS_RESERVED = new Set([
  "arguments", "await", "break", "case", "catch", "class", "const", "continue", "debugger",
  "default", "delete", "do", "else", "enum", "eval", "export", "extends", "false", "finally",
  "for", "function", "if", "implements", "import", "in", "instanceof", "interface", "let", "new",
  "null", "package", "private", "protected", "public", "return", "static", "super", "switch",
  "this", "throw", "true", "try", "typeof", "var", "void", "while", "with", "yield",
]);
const JS_RENAMES = { package: "pkg" };

const problems = [];
const fail = (where, msg) => problems.push(`${where}: ${msg}`);

const pascal = (s) => s.split(/[._]/).filter(Boolean).map((w) => w[0].toUpperCase() + w.slice(1)).join("");
const camel = (s) => s.replace(/_([a-z0-9])/g, (_, ch) => ch.toUpperCase());
const typeName = (s) => (HANDWRITTEN_CLASSES.has(pascal(s)) ? `${pascal(s)}Info` : pascal(s));
const en = (doc) => clean(doc?.en ?? "");
const sentence = (s) => (s && !/[.!?:]$/.test(s) ? `${s}.` : s);

// The project style bans the em dash, including in text copied from the spec.
const EM_DASH = new RegExp(String.fromCharCode(0x2014), "g");

function clean(text) {
  return String(text).replace(EM_DASH, "-").replace(/\s+/g, " ").trim();
}

function splitTop(text, sep) {
  const parts = [];
  let depth = 0;
  let start = 0;
  for (let i = 0; i < text.length; i++) {
    const ch = text[i];
    if (ch === "<" || ch === "(" || ch === "[") depth++;
    else if (ch === ">" || ch === ")" || ch === "]") depth--;
    else if (ch === sep && depth === 0) {
      parts.push(text.slice(start, i));
      start = i + 1;
    }
  }
  parts.push(text.slice(start));
  return parts.map((p) => p.trim());
}

function parseType(text) {
  const members = splitTop(text, "|");
  if (members.length > 1) return { union: members.map(parseType) };
  const list = /^list<(.+)>$/.exec(text.trim());
  if (list) return { list: parseType(list[1]) };
  return { name: text.trim() };
}

function checkType(type, where, typeNames) {
  if (type.union) return type.union.forEach((t) => checkType(t, where, typeNames));
  if (type.list) return checkType(type.list, where, typeNames);
  if (!BASE_TYPES.has(type.name) && !typeNames.has(type.name)) fail(where, `unknown type "${type.name}"`);
}

function typeIncludes(type, name) {
  if (type.union) return type.union.some((t) => typeIncludes(t, name));
  if (type.list) return typeIncludes(type.list, name);
  return type.name === name;
}

function resolveParam(raw, common, where) {
  let p = raw;
  if (raw.ref !== undefined) {
    const base = common[raw.ref];
    if (!base) {
      fail(where, `unknown param ref "${raw.ref}"`);
      return null;
    }
    const { ref, ...rest } = raw;
    p = { ...base, ...rest, name: ref };
  }
  if (typeof p.name !== "string" || !/^[A-Za-z_][A-Za-z0-9_]*$/.test(p.name)) {
    fail(where, `param name ${JSON.stringify(p.name)} is not a valid identifier`);
    return null;
  }
  if (typeof p.type !== "string") {
    fail(where, `param "${p.name}" has no type`);
    return null;
  }
  return {
    name: p.name,
    type: parseType(p.type),
    rawType: p.type,
    required: p.required === true,
    hasDefault: Object.prototype.hasOwnProperty.call(p, "default"),
    default: p.default,
    enum: p.enum,
    doc: en(p.doc),
    clientOnly: p.client_only === true,
  };
}

function loadModel(spec) {
  const typeNames = new Set(Object.keys(spec.types ?? {}));
  const common = spec.common_params ?? {};
  const selectors = (spec.selectors ?? []).map((s) => s.by);

  const errors = [];
  const errorCodes = new Map();
  for (const e of spec.errors ?? []) {
    const where = `error "${e.code}"`;
    if (typeof e.code !== "string" || !/^[A-Z][A-Z0-9_]*$/.test(e.code)) fail(where, "code must be UPPER_SNAKE_CASE");
    if (errorCodes.has(e.code)) fail(where, "duplicate error code");
    if (typeof e.retryable !== "boolean") fail(where, "retryable must be true or false");
    let pyName = `${pascal(e.code.toLowerCase())}Error`;
    if (PY_BUILTIN_EXCEPTIONS.has(pyName)) pyName = `Droidline${pyName}`;
    const err = { code: e.code, http: e.http, retryable: e.retryable === true, doc: en(e.doc), pyName };
    errorCodes.set(e.code, err);
    errors.push(err);
  }

  const commands = [];
  const seen = new Map();
  const claim = (name, where) => {
    if (seen.has(name)) {
      fail(where, `name "${name}" is already used by ${seen.get(name)}`);
      return false;
    }
    seen.set(name, where);
    return true;
  };

  for (const c of spec.commands ?? []) {
    const where = `command "${c.name}"`;
    if (typeof c.name !== "string" || !/^[a-z][a-z0-9_]*(\.[a-z][a-z0-9_]*)?$/.test(c.name)) {
      fail(where, "name must be snake_case, optionally namespace.method");
      continue;
    }
    if (!claim(c.name, where)) continue;
    // Handwritten in each SDK, like lease(), which returns a phone object instead of the raw reply.
    if (c.sdk_manual === true) continue;
    if (!SCOPES.has(c.scope)) fail(where, `unknown scope "${c.scope}"`);
    if (!en(c.summary)) fail(where, "summary.en is missing");

    const params = [];
    const paramNames = new Set();
    let sawOptional = false;
    for (const raw of c.params ?? []) {
      const p = resolveParam(raw, common, where);
      if (!p) continue;
      if (paramNames.has(p.name)) fail(where, `duplicate param "${p.name}"`);
      paramNames.add(p.name);
      checkType(p.type, `${where} param "${p.name}"`, typeNames);
      if (PY_KEYWORDS.has(p.name)) fail(where, `param "${p.name}" is a Python keyword`);
      if (p.required && sawOptional) fail(where, `required param "${p.name}" follows an optional one`);
      // value is optional only because a query object replaces it; selectorShape handles what follows.
      if (!p.required && !(p.name === "value" && paramNames.has("by"))) sawOptional = true;
      if (p.enum && p.hasDefault && !p.enum.includes(p.default)) fail(where, `default of "${p.name}" is not in its enum`);
      if (p.enum && p.type.name !== "string") fail(where, `enum on "${p.name}" needs type string`);
      if (!p.required && (typeIncludes(p.type, "object") || typeIncludes(p.type, "node"))) {
        fail(where, `optional param "${p.name}" may be a plain object, which the Node SDK reads as the options argument`);
      }
      params.push(p);
    }
    if (c.scope === "device" && paramNames.has("device")) fail(where, `device commands cannot have a "device" param`);
    if (c.sdk_wrap !== undefined) {
      const t = c.returns?.type;
      if (c.sdk_wrap !== "element") fail(where, `unknown sdk_wrap "${c.sdk_wrap}"`);
      else if (c.returns?.kind !== "value" || (t !== "node" && t !== "list<node>")) fail(where, `sdk_wrap "element" needs returns value node or list<node>`);
      if (c.scope !== "device" || c.name.includes(".")) fail(where, "sdk_wrap is only for top-level device commands");
    }

    const returns = c.returns ?? {};
    if (!KINDS.has(returns.kind)) fail(where, `unknown returns.kind "${returns.kind}"`);
    let valueType = null;
    let fields = [];
    if (returns.kind === "value") {
      if (typeof returns.type !== "string") fail(where, "returns.type is missing");
      else {
        valueType = parseType(returns.type);
        checkType(valueType, `${where} returns`, typeNames);
      }
    }
    if (returns.kind === "fields") {
      fields = (returns.fields ?? []).map((f) => ({ name: f.name, type: parseType(f.type) }));
      fields.forEach((f) => checkType(f.type, `${where} returns field "${f.name}"`, typeNames));
      if (fields.some((f) => f.name === "id" || f.name === "ok")) fail(where, `returns.fields cannot contain id or ok`);
    }

    for (const code of c.errors ?? []) {
      if (!errorCodes.has(code)) fail(where, `unknown error code "${code}"`);
    }

    if (c.sdk_save !== undefined) {
      if (!SAVE_MODES.has(c.sdk_save)) fail(where, `unknown sdk_save "${c.sdk_save}"`);
      const path = params.find((p) => p.name === "path");
      if (!path || !path.clientOnly || path.required) fail(where, "sdk_save needs an optional client_only param named path");
      if (returns.kind !== "fields") fail(where, "sdk_save needs returns.kind fields");
      if (c.sdk_save === "image" && !fields.some((f) => f.name === "data")) fail(where, `sdk_save "image" needs a data field`);
      if (c.name.includes(".")) fail(where, "sdk_save is not supported on namespaced commands");
    } else if (c.scope !== "client" && params.some((p) => p.clientOnly)) {
      fail(where, "client_only params need sdk_save or scope client");
    }

    let cuts = null;
    if (c.cuts_network !== undefined) {
      const p = params.find((x) => x.name === c.cuts_network.param);
      if (!p) fail(where, `cuts_network.param "${c.cuts_network.param}" is not a param`);
      cuts = { param: c.cuts_network.param, when: c.cuts_network.when };
    }
    // A batch can hold a network-cutting step, so it takes the wait flag as well (PROTOCOL 3.2).
    const takesWait = cuts !== null || params.some((p) => typeIncludes(p.type, "step"));
    if (takesWait && paramNames.has("wait")) fail(where, `param "wait" clashes with the wait flag`);

    const aliases = [];
    for (const a of c.aliases ?? []) {
      const awhere = `${where} alias "${a.name}"`;
      if (typeof a.name !== "string" || !/^[a-z][A-Za-z0-9]*$/.test(a.name)) fail(awhere, "alias must be camelCase");
      claim(a.name, awhere);
      if (!paramNames.has("by")) fail(awhere, `command has no "by" param`);
      if (!selectors.includes(a.by)) fail(awhere, `unknown selector "${a.by}"`);
      aliases.push({ name: a.name, by: a.by });
    }

    commands.push({
      name: c.name,
      scope: c.scope,
      group: c.group,
      summary: sentence(en(c.summary)),
      notes: sentence(en(c.notes)),
      params,
      kind: returns.kind,
      valueType,
      fields,
      errors: (c.errors ?? []).filter((code) => errorCodes.has(code)).map((code) => errorCodes.get(code)),
      save: c.sdk_save ?? null,
      wrap: c.sdk_wrap ?? null,
      cuts,
      takesWait,
      aliases,
      example: typeof c.example === "string" ? c.example : null,
    });
  }

  for (const s of spec.selectors ?? []) {
    if (!s.shorthand) continue;
    const owner = commands.find((c) => c.aliases.some((a) => a.name === s.shorthand));
    if (!owner) fail(`selector "${s.by}"`, `shorthand "${s.shorthand}" is not an alias of any command`);
    else if (!owner.aliases.some((a) => a.name === s.shorthand && a.by === s.by)) {
      fail(`selector "${s.by}"`, `shorthand "${s.shorthand}" maps to a different selector in its alias`);
    }
  }

  for (const b of spec.batch_only ?? []) claim(b.name, `batch_only "${b.name}"`);

  const onDevice = commands.filter((c) => c.scope === "device" || (c.scope === "server" && c.group !== "server"));
  const onClient = commands.filter((c) => c.scope === "server");

  const namespaces = new Map();
  for (const c of onDevice.filter((x) => x.name.includes("."))) {
    const ns = c.name.split(".")[0];
    if (!namespaces.has(ns)) namespaces.set(ns, []);
    namespaces.get(ns).push(c);
  }
  for (const ns of namespaces.keys()) {
    if (onDevice.some((c) => c.name === ns)) fail(`namespace "${ns}"`, "clashes with a command of the same name");
  }

  const checkMembers = (list, owner) => {
    const taken = new Set();
    for (const c of list.filter((x) => !x.name.includes("."))) {
      const names = [c.name, ...c.aliases.map((a) => a.name)];
      if (c.name.includes("_")) names.push(camel(c.name));
      for (const n of names) {
        if (RESERVED[owner].includes(n)) fail(`command "${c.name}"`, `"${n}" clashes with a handwritten ${owner} member`);
        if (taken.has(n)) fail(`command "${c.name}"`, `"${n}" is generated twice on the ${owner} class`);
        taken.add(n);
      }
    }
    if (owner === "device") for (const ns of namespaces.keys()) if (taken.has(ns)) fail(`namespace "${ns}"`, "clashes with a method");
  };
  checkMembers(onDevice, "device");
  checkMembers(onClient, "client");

  const types = Object.entries(spec.types ?? {}).map(([name, t]) => ({
    name,
    tName: typeName(name),
    doc: sentence(en(t.doc)),
    fields: t.fields ?? [],
  }));

  const queryKeys = (spec.query?.keys ?? []).map((k) => {
    if (!["string", "bool", "bounds", "query"].includes(k.type)) fail(`query key "${k.key}"`, `unknown type "${k.type}"`);
    return { key: k.key, type: k.type, doc: sentence(en(k.doc)) };
  });

  return {
    proto: spec.proto,
    selectors,
    queryKeys,
    queryDoc: sentence(en(spec.query?.doc)),
    errors,
    types,
    typeNames: new Map(types.map((t) => [t.name, t.tName])),
    onDevice: onDevice.filter((c) => !c.name.includes(".")),
    onClient,
    namespaces,
  };
}

// Each generated SDK method; aliases get their own entry with the selector fixed.
function methodsOf(cmd) {
  const base = {
    cmd,
    wire: cmd.name,
    method: cmd.name.includes(".") ? cmd.name.split(".")[1] : cmd.name,
    params: cmd.params,
    aliasBy: null,
  };
  const aliases = cmd.aliases.map((a) => ({
    cmd,
    wire: a.name,
    method: a.name,
    params: cmd.params.filter((p) => p.name !== "by").map((p) => (p.name === "value" ? { ...p, required: true } : p)),
    aliasBy: a.by,
  }));
  return [base, ...aliases];
}

// Commands with by and value: a query object in by replaces value, and required params
// after value (input's text) move up one place when the caller passes a query.
function selectorShape(meth) {
  if (meth.aliasBy) return null;
  const vi = meth.params.findIndex((p) => p.name === "value");
  if (vi < 0 || !meth.params.some((p) => p.name === "by")) return null;
  const shift = meth.params.slice(vi + 1).filter((p) => p.required).map((p) => p.name);
  if (shift.length > 1) fail(`command "${meth.cmd.name}"`, "only one required param may follow value");
  return { shift };
}

function defaultNote(p, literal) {
  return p.hasDefault ? ` Default: ${literal(p.default)}.` : "";
}

function waitDoc(cmd, lang) {
  const t = lang === "py" ? { true: "True", false: "False", acc: '{"accepted": True}' } : { true: "true", false: "false", acc: "{ accepted: true }" };
  const verb = lang === "py" ? "returns" : "resolves with";
  const lead = lang === "py" ? "Block until the phone is back and return the final result." : "Resolve with the final result once the phone is back.";
  const val = cmd.cuts ? t[String(cmd.cuts.when)] ?? JSON.stringify(cmd.cuts.when) : "";
  let call = `a ${cmd.name} with a step that cuts the network`;
  if (cmd.cuts && cmd.params[0]?.name === cmd.cuts.param) call = `${cmd.name}(${val})`;
  else if (cmd.cuts) call = lang === "py" ? `${cmd.name}(..., ${cmd.cuts.param}=${val})` : `${cmd.name}(..., { ${cmd.cuts.param}: ${val} })`;
  return `${lead} Without it, ${call} ${verb} ${t.acc} as soon as the phone accepts, and the final result arrives later as a "result" event.`;
}

// Turns the Python-flavoured spec example into JavaScript: tuples become arrays, keyword args an options object.
function jsExample(example) {
  const strings = [];
  const masked = example.replace(/"(?:[^"\\]|\\.)*"/g, (s) => {
    strings.push(s);
    return `\u0000${strings.length - 1}\u0000`;
  });
  const call = /^([A-Za-z_][\w.]*)\((.*)\)$/.exec(masked);
  if (!call) return null;
  let body = call[2].replace(/\bTrue\b/g, "true").replace(/\bFalse\b/g, "false").replace(/\bNone\b/g, "null");
  const stack = [];
  let out = "";
  for (let i = 0; i < body.length; i++) {
    const ch = body[i];
    if (ch === "(") {
      const isCall = /[\w]$/.test(out);
      stack.push(isCall);
      out += isCall ? "(" : "[";
    } else if (ch === ")") {
      out += stack.pop() ? ")" : "]";
    } else out += ch;
  }
  body = out;
  const args = body ? splitTop(body, ",") : [];
  const positional = [];
  const named = [];
  for (const a of args) {
    const kw = /^([A-Za-z_]\w*)=(?!=)(.*)$/.exec(a);
    if (kw) named.push(`${kw[1]}: ${kw[2].trim()}`);
    else if (named.length) return null;
    else positional.push(a);
  }
  if (named.length) positional.push(`{ ${named.join(", ")} }`);
  const js = `${call[1]}(${positional.join(", ")})`;
  return js.replace(/\u0000(\d+)\u0000/g, (_, i) => strings[Number(i)]);
}

function pyLiteral(v) {
  if (v === true) return "True";
  if (v === false) return "False";
  if (v === null) return "None";
  if (Array.isArray(v)) return `[${v.map(pyLiteral).join(", ")}]`;
  return typeof v === "string" ? JSON.stringify(v) : String(v);
}

function pyType(type, m, ctx, enumValues) {
  if (enumValues) return `Literal[${enumValues.map(pyLiteral).join(", ")}]`;
  if (type.union) {
    const rest = type.union.filter((t) => t.name !== "null").map((t) => pyType(t, m, ctx));
    const inner = rest.length === 1 ? rest[0] : `Union[${rest.join(", ")}]`;
    return rest.length < type.union.length ? `Optional[${inner}]` : inner;
  }
  if (type.list) return `${ctx === "param" ? "Sequence" : "List"}[${pyType(type.list, m, ctx)}]`;
  const map = {
    string: "str", int: "int", number: "float", bool: "bool", null: "None", base64: "str",
    object: "Dict[str, Any]", function: "Callable[..., Any]", selector: "Union[By, Query]",
    selector_pair: "Union[Tuple[By, str], Query]", step: "Step", image: "Union[str, bytes]",
  };
  return map[type.name] ?? m.typeNames.get(type.name);
}

function pyString(text, indent) {
  const body = text.replace(/\\/g, "\\\\").replace(/"""/g, '\\"\\"\\"');
  const lines = body.split("\n").map((l) => (l ? indent + l : ""));
  return `${indent}"""${lines.join("\n").slice(indent.length)}\n${indent}"""`;
}

function pyDocLine(text) {
  return `"""${text.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"""`;
}

function pyTypedDict(name, entries, total) {
  const tail = total ? "" : ", total=False";
  const one = `${name} = TypedDict(${JSON.stringify(name)}, {${entries.join(", ")}}${tail})`;
  if (one.length <= 99) return one;
  return [`${name} = TypedDict(`, `    ${JSON.stringify(name)},`, "    {", ...entries.map((e) => `        ${e},`), "    },", ...(total ? [] : ["    total=False,"]), ")"].join("\n");
}

function pyResultName(cmd) {
  return `${pascal(cmd.name)}Result`;
}

function pyReturn(cmd, m) {
  if (cmd.wrap) return cmd.valueType.list ? "List[Element]" : "Element";
  if (cmd.kind === "value") return pyType(cmd.valueType, m, "return");
  if (cmd.kind === "fields") return pyResultName(cmd);
  return "None";
}

function pyDocstring(meth, owner, m) {
  const { cmd } = meth;
  const parts = [];
  let head = cmd.summary;
  if (meth.aliasBy) head = `${cmd.summary} Shorthand for ${cmd.name}(${JSON.stringify(meth.aliasBy)}, value).`;
  parts.push(head);
  if (cmd.notes) parts.push(cmd.notes);
  const args = meth.params.map((p) => `    ${p.name}: ${sentence(p.doc)}${defaultNote(p, pyLiteral)}`.trimEnd());
  if (cmd.takesWait) args.push(`    wait: ${waitDoc(cmd, "py")}`);
  if (args.length) parts.push(["Args:", ...args].join("\n"));
  if (cmd.errors.length) parts.push(["Raises:", ...cmd.errors.map((e) => `    ${e.pyName}: ${e.doc}`)].join("\n"));
  if (cmd.example && !meth.aliasBy) {
    const receiver = owner === "client" ? "client" : "d";
    parts.push(`Example:\n    ${receiver}.${cmd.example}`);
  }
  return parts.join("\n\n");
}

// The hooks return Any, so typed results go through cast() to keep mypy --strict quiet.
function pyCallLine(fn, args, ret, indent) {
  const head = ret === "None" ? "" : `return cast(${JSON.stringify(ret)}, `;
  const tail = ret === "None" ? "" : ")";
  const one = `${indent}${head}self.${fn}(${args.join(", ")})${tail}`;
  if (one.length <= 99) return [one];
  return [`${indent}${head}self.${fn}(`, ...args.map((a) => `${indent}    ${a},`), `${indent})${tail}`];
}

function pySignature(name, params, ret, indent, decorator) {
  const one = `${indent}def ${name}(${["self", ...params].join(", ")}) -> ${ret}:`;
  const lines = decorator ? [`${indent}${decorator}`] : [];
  if (one.length <= 99) return [...lines, one];
  return [...lines, `${indent}def ${name}(`, `${indent}    self,`, ...params.map((p) => `${indent}    ${p},`), `${indent}) -> ${ret}:`];
}

function pyMethod(meth, owner, m, runner) {
  const { cmd } = meth;
  const ind = "    ";
  const shape = selectorShape(meth);
  const sig = meth.params.map((p) => {
    const t = pyType(p.type, m, "param", p.enum);
    if (p.required && !shape?.shift.includes(p.name)) return `${p.name}: ${t}`;
    return `${p.name}: ${t.startsWith("Optional[") ? t : `Optional[${t}]`} = None`;
  });
  if (cmd.takesWait) sig.push("*", "wait: Optional[bool] = None");
  const required = meth.params.filter((p) => p.required);
  const optional = meth.params.filter((p) => !p.required && p.name !== "path");
  const reqDict = `{${required.map((p) => `${JSON.stringify(p.name)}: ${p.name}`).join(", ")}}`;
  const kw = optional.map((p) => `${p.name}=${p.name}`);
  if (cmd.takesWait) kw.push("wait=wait");
  const doc = pyString(pyDocstring(meth, owner, m), ind + ind);

  const lines = [];
  if (cmd.save === "image") {
    const rest = sig.slice(1);
    lines.push(...pySignature(meth.method, ["path: None = None", ...rest], "bytes", ind, "@overload"));
    lines.push(`${ind}${ind}...`, "");
    lines.push(...pySignature(meth.method, ["path: str", ...rest], "str", ind, "@overload"));
    lines.push(`${ind}${ind}...`, "");
    lines.push(...pySignature(meth.method, sig, "Union[bytes, str]", ind));
    lines.push(doc);
    lines.push(...pyCallLine(`${runner.save}_image`, [JSON.stringify(meth.wire), "path", reqDict, ...kw], "Union[bytes, str]", ind + ind));
  } else if (cmd.save === "json") {
    lines.push(...pySignature(meth.method, sig, pyResultName(cmd), ind));
    lines.push(doc);
    lines.push(...pyCallLine(`${runner.save}_json`, [JSON.stringify(meth.wire), "path", reqDict, ...kw], pyResultName(cmd), ind + ind));
  } else {
    lines.push(...pySignature(meth.method, sig, pyReturn(cmd, m), ind));
    lines.push(doc);
    for (const name of shape?.shift ?? []) {
      lines.push(`${ind}${ind}if not isinstance(by, str) and ${name} is None:`);
      lines.push(`${ind}${ind}${ind}value, ${name} = None, value`);
    }
    for (const p of meth.params.filter((x) => x.type.name === "image")) {
      lines.push(`${ind}${ind}${p.name} = self._load_image(${p.name})`);
    }
    const hook = cmd.wrap ? `${runner.run}_element` : runner.run;
    lines.push(...pyCallLine(hook, [JSON.stringify(meth.wire), JSON.stringify(cmd.kind), reqDict, ...kw], pyReturn(cmd, m), ind + ind));
  }
  return lines.join("\n");
}

function renderPython(m) {
  const L = [];
  L.push(`# ${HEADER}`);
  L.push(`"""Command methods, result types and error classes for Droidline protocol ${m.proto}."""`);
  L.push("");
  L.push("from __future__ import annotations");
  L.push("");
  L.push("from typing import TYPE_CHECKING, Any, Callable, Dict, List, Literal, Mapping, Optional, Sequence, Tuple, Type, TypedDict, Union, cast, overload");
  L.push("");
  L.push("from ._errors import DroidlineError");
  L.push("");
  L.push("if TYPE_CHECKING:");
  L.push("    from ._element import Element");
  L.push("");
  L.push(`PROTO = ${m.proto}`);
  L.push("");
  L.push(`By = Literal[${m.selectors.map(pyLiteral).join(", ")}]`);
  L.push("Step = Union[Sequence[Any], Mapping[str, Any]]");
  L.push("");
  const pyQueryType = { string: "str", bool: "bool", bounds: "Sequence[int]", query: '"Query"' };
  L.push(pyTypedDict("Query", m.queryKeys.map((k) => `${JSON.stringify(k.key)}: ${pyQueryType[k.type]}`), false));
  if (m.queryDoc) L.push(pyDocLine(m.queryDoc));
  L.push("");

  for (const t of m.types) {
    L.push(pyTypedDict(t.tName, t.fields.map((f) => `${JSON.stringify(f)}: Any`), false));
    if (t.doc) L.push(pyDocLine(t.doc));
    L.push("");
  }

  const fieldCommands = [...new Set([...m.onDevice, ...m.onClient, ...[...m.namespaces.values()].flat()])].filter((c) => c.kind === "fields");
  for (const c of fieldCommands) {
    const fields = c.fields.map((f) => `${JSON.stringify(f.name)}: ${pyType(f.type, m, "return")}`);
    if (c.takesWait) fields.push('"accepted": bool');
    L.push(pyTypedDict(pyResultName(c), fields, !c.takesWait));
  }
  L.push("", "");

  for (const e of m.errors) {
    L.push(`class ${e.pyName}(DroidlineError):`);
    L.push(`    ${pyDocLine(e.doc)}`);
    L.push("");
    L.push(`    code = ${JSON.stringify(e.code)}`);
    L.push(`    http = ${e.http}`);
    L.push(`    retryable = ${pyLiteral(e.retryable)}`);
    L.push("", "");
  }
  L.push("ERRORS: Dict[str, Type[DroidlineError]] = {");
  for (const e of m.errors) L.push(`    ${JSON.stringify(e.code)}: ${e.pyName},`);
  L.push("}");
  L.push("", "");

  const hooks = (save) => {
    const out = [
      "    def _run(self, cmd: str, kind: str, required: Dict[str, Any], /, **optional: Any) -> Any:",
      "        raise NotImplementedError",
    ];
    if (save) {
      out.push("");
      out.push("    def _run_element(self, cmd: str, kind: str, required: Dict[str, Any], /, **optional: Any) -> Any:");
      out.push("        raise NotImplementedError");
      out.push("");
      out.push("    def _load_image(self, image: Union[str, bytes]) -> str:");
      out.push("        raise NotImplementedError");
      for (const mode of ["image", "json"]) {
        out.push("");
        out.push(`    def _save_${mode}(self, cmd: str, path: Optional[str], required: Dict[str, Any], /, **optional: Any) -> Any:`);
        out.push("        raise NotImplementedError");
      }
    }
    return out;
  };

  for (const [ns, cmds] of m.namespaces) {
    L.push(`class ${pascal(ns)}Commands:`);
    L.push(`    """The ${ns}.* commands, reached as d.${ns}."""`);
    L.push("");
    L.push("    def __init__(self, owner: DeviceCommands) -> None:");
    L.push("        self._owner = owner");
    for (const c of cmds) {
      for (const meth of methodsOf(c)) {
        L.push("");
        L.push(pyMethod(meth, "device", m, { run: "_owner._run", save: "_owner._save" }));
      }
    }
    L.push("", "");
  }

  L.push("class DeviceCommands:");
  L.push('    """Commands that run on one phone. Device mixes these in and implements _run."""');
  L.push("");
  L.push(...hooks(true));
  for (const ns of m.namespaces.keys()) {
    L.push("");
    L.push("    @property");
    L.push(`    def ${ns}(self) -> ${pascal(ns)}Commands:`);
    L.push(`        return ${pascal(ns)}Commands(self)`);
  }
  for (const c of m.onDevice) {
    for (const meth of methodsOf(c)) {
      L.push("");
      L.push(pyMethod(meth, "device", m, { run: "_run", save: "_save" }));
    }
  }
  L.push("", "");

  L.push("class ClientCommands:");
  L.push('    """Commands the PC server answers itself. Droidline mixes these in and implements _run."""');
  L.push("");
  L.push(...hooks(false));
  for (const c of m.onClient) {
    for (const meth of methodsOf(c)) {
      L.push("");
      L.push(pyMethod(meth, "client", m, { run: "_run", save: "_save" }));
    }
  }
  L.push("", "");

  const exported = [
    "PROTO", "By", "Query", "Step", ...m.types.map((t) => t.tName), ...fieldCommands.map(pyResultName),
    ...m.errors.map((e) => e.pyName), "ERRORS", ...[...m.namespaces.keys()].map((ns) => `${pascal(ns)}Commands`),
    "DeviceCommands", "ClientCommands",
  ];
  L.push("__all__ = [");
  for (const name of exported) L.push(`    ${JSON.stringify(name)},`);
  L.push("]");
  L.push("");
  return L.join("\n");
}

function tsType(type, m, ctx, enumValues) {
  if (enumValues) return enumValues.map((v) => JSON.stringify(v)).join(" | ");
  if (type.union) return type.union.map((t) => tsType(t, m, ctx)).join(" | ");
  if (type.list) {
    const inner = tsType(type.list, m, ctx);
    return ctx === "param" ? `ReadonlyArray<${inner}>` : `Array<${inner}>`;
  }
  const map = {
    string: "string", int: "number", number: "number", bool: "boolean", null: "null", base64: "string",
    object: "Record<string, any>", function: "(...args: any[]) => unknown", selector: "By | Query",
    selector_pair: "readonly [By, string] | Query", step: "Step", image: "string | Uint8Array",
  };
  return map[type.name] ?? m.typeNames.get(type.name);
}

function tsIdent(name) {
  if (JS_RENAMES[name]) return JS_RENAMES[name];
  return JS_RESERVED.has(name) ? `${name}_` : name;
}

function tsComment(text, indent) {
  const body = text.replace(/\*\//g, "*\\/").split("\n");
  if (body.length === 1) return `${indent}/** ${body[0]} */`;
  return [`${indent}/**`, ...body.map((l) => (l ? `${indent} * ${l}` : `${indent} *`)), `${indent} */`].join("\n");
}

const tsResultName = (cmd) => `${pascal(cmd.name)}Result`;
const tsOptionsName = (cmd) => `${pascal(cmd.name)}Options`;
const hasOptions = (cmd) => cmd.takesWait || cmd.params.some((p) => !p.required && p.name !== "path");

function tsReturn(cmd, m) {
  if (cmd.wrap) return cmd.valueType.list ? "Element[]" : "Element";
  if (cmd.kind === "value") return tsType(cmd.valueType, m, "return");
  if (cmd.kind === "fields") return tsResultName(cmd);
  return "void";
}

function tsDoc(meth, owner, alias) {
  const { cmd } = meth;
  const parts = [];
  parts.push(meth.aliasBy ? `${cmd.summary} Shorthand for ${cmd.name}(${JSON.stringify(meth.aliasBy)}, value).` : cmd.summary);
  if (cmd.notes) parts.push(cmd.notes);
  const documented = cmd.save ? meth.params.filter((p) => p.required || p.name === "path") : meth.params;
  const tags = documented.map((p) => `@param ${tsIdent(p.name)} ${sentence(p.doc)}${defaultNote(p, JSON.stringify)}`.trimEnd());
  if (hasOptions(cmd)) tags.push(`@param opts Optional parameters by name, see ${tsOptionsName(cmd)}.`);
  if (cmd.errors.length) tags.push(`@throws {DroidlineError} with code ${cmd.errors.map((e) => e.code).join(", ")}.`);
  if (cmd.example && !meth.aliasBy) {
    const js = jsExample(cmd.example);
    if (js) tags.push(`@example await ${owner === "client" ? "client" : "d"}.${js}`);
  }
  if (alias) tags.push(`@alias ${alias}`);
  parts.push(tags.join("\n"));
  return parts.filter(Boolean).join("\n\n");
}

function tsMethod(meth, owner, m, name, alias) {
  const { cmd } = meth;
  const shape = selectorShape(meth);
  const ind = "  ";
  const doc = tsComment(tsDoc(meth, owner, alias), ind);
  const req = meth.params.filter((p) => p.required);
  const opt = meth.params.filter((p) => !p.required);
  const reqSig = req.map((p) => `${tsIdent(p.name)}: ${tsType(p.type, m, "param", p.enum)}`);
  const optsArg = hasOptions(cmd) ? [`opts?: ${tsOptionsName(cmd)}`] : [];
  const lines = [];
  const overload = (params, ret) => {
    lines.push(doc);
    lines.push(`${ind}${name}(${params.join(", ")}): Promise<${ret}>;`);
  };

  let ret = tsReturn(cmd, m);
  let positional = opt.map((p) => p.name);
  let hook = "_run";
  if (cmd.save === "image") {
    overload([...reqSig, ...optsArg], "Buffer");
    overload([...reqSig, "path: string", ...optsArg], "string");
    ret = "Buffer | string";
    positional = ["path"];
    hook = "_saveImage";
  } else if (cmd.save === "json") {
    overload([...reqSig, ...optsArg], ret);
    overload([...reqSig, "path: string", ...optsArg], ret);
    positional = ["path"];
    hook = "_saveJson";
  } else if (shape) {
    // Two forms: (by, value, ...) for a field selector, (query, ...) where the query replaces value.
    const after = opt.filter((p) => p.name !== "value");
    const optSig = after.map((p) => `${tsIdent(p.name)}?: ${tsType(p.type, m, "param", p.enum)}`);
    const shiftSig = meth.params.filter((p) => shape.shift.includes(p.name)).map((p) => `${tsIdent(p.name)}: ${tsType(p.type, m, "param", p.enum)}`);
    const reqOthers = reqSig.filter((_, i) => req[i].name !== "by" && !shape.shift.includes(req[i].name));
    for (let k = 0; k <= optSig.length; k++) overload(["by: By", "value: string", ...shiftSig, ...reqOthers, ...optSig.slice(0, k), ...optsArg], ret);
    for (let k = 0; k <= optSig.length; k++) overload(["by: Query", ...shiftSig, ...reqOthers, ...optSig.slice(0, k), ...optsArg], ret);
    positional = after.map((p) => p.name);
  } else {
    // One overload per prefix of positional optionals, each closed by the options object.
    const optSig = opt.map((p) => `${tsIdent(p.name)}?: ${tsType(p.type, m, "param", p.enum)}`);
    for (let k = 0; k <= optSig.length; k++) overload([...reqSig, ...optSig.slice(0, k), ...optsArg], ret);
  }
  const list = (names) => `[${names.map((n) => JSON.stringify(n)).join(", ")}]`;
  let collectArgs = `collect(${JSON.stringify(meth.wire)}, args, ${list(req.map((p) => p.name))}, ${list(positional)})`;
  if (shape && !cmd.save) {
    const reqNames = req.map((p) => p.name).filter((n) => n !== "by");
    const forField = list(["by", "value", ...reqNames]);
    const forQuery = list(["by", ...reqNames]);
    collectArgs = `collect(${JSON.stringify(meth.wire)}, args, typeof args[0] === "string" ? ${forField} : ${forQuery}, ${list(positional)})`;
  }
  lines.push(`${ind}async ${name}(...args: unknown[]): Promise<${ret}> {`);
  const images = meth.params.filter((p) => p.type.name === "image").map((p) => p.name);
  if (images.length && !cmd.save) {
    lines.push(`${ind}  const params = ${collectArgs};`);
    for (const n of images) lines.push(`${ind}  params[${JSON.stringify(n)}] = await this._loadImage(params[${JSON.stringify(n)}]);`);
    collectArgs = "params";
  }
  if (cmd.save) lines.push(`${ind}  return this.${hook}(${JSON.stringify(meth.wire)}, ${collectArgs});`);
  else lines.push(`${ind}  return this.${cmd.wrap ? "_runElement" : "_run"}(${JSON.stringify(meth.wire)}, ${JSON.stringify(cmd.kind)}, ${collectArgs});`);
  lines.push(`${ind}}`);
  return lines.join("\n");
}

function tsMethods(cmd, owner, m) {
  const out = [];
  for (const meth of methodsOf(cmd)) {
    out.push(tsMethod(meth, owner, m, meth.method, null));
    if (meth.method.includes("_")) out.push(tsMethod(meth, owner, m, camel(meth.method), meth.method));
  }
  return out;
}

function tsInterface(name, doc, members, open = false) {
  const lines = [];
  if (doc) lines.push(tsComment(doc, ""));
  lines.push(`export interface ${name} {`);
  for (const mem of members) {
    if (mem.doc) lines.push(tsComment(mem.doc, "  "));
    const key = /^[A-Za-z_$][\w$]*$/.test(mem.name) ? mem.name : JSON.stringify(mem.name);
    lines.push(`  ${key}${mem.optional ? "?" : ""}: ${mem.type};`);
  }
  if (open) lines.push("  [field: string]: any;");
  lines.push("}");
  return lines.join("\n");
}

function renderTs(m) {
  const L = [];
  L.push(`// ${HEADER}`);
  L.push('import { EventEmitter } from "node:events";');
  L.push('import { collect, type Params } from "./args.js";');
  L.push('import type { Element } from "./element.js";');
  L.push("");
  L.push(`export const PROTO = ${m.proto};`);
  L.push("");
  L.push('export type ReturnKind = "value" | "fields" | "none";');
  L.push("");
  L.push("/** Which dump field a selector matches. */");
  L.push(`export type By = ${m.selectors.map((s) => JSON.stringify(s)).join(" | ")};`);
  L.push("");
  const tsQueryType = { string: "string", bool: "boolean", bounds: "readonly [number, number, number, number]", query: "Query" };
  L.push(tsInterface("Query", m.queryDoc, m.queryKeys.map((k) => ({ name: k.key, type: tsQueryType[k.type], optional: true, doc: k.doc }))));
  L.push("");
  L.push("/** One batch step: [cmd, ...args] or { cmd, ...params }. */");
  L.push("export type Step = ReadonlyArray<unknown> | { readonly cmd: string; readonly [param: string]: unknown };");
  L.push("");

  for (const t of m.types) {
    L.push(tsInterface(t.tName, t.doc, t.fields.map((f) => ({ name: f, type: "any", optional: true })), true));
    L.push("");
  }

  L.push("/** Error codes the server can answer with, from spec/commands.json. */");
  L.push(`export type ErrorCode =\n${m.errors.map((e) => `  | ${JSON.stringify(e.code)}`).join("\n")};`);
  L.push("");
  L.push("/** HTTP status and default retryable flag of each error code. */");
  L.push("export const ERRORS: Readonly<Record<ErrorCode, { readonly http: number; readonly retryable: boolean }>> = {");
  for (const e of m.errors) {
    L.push(tsComment(e.doc, "  "));
    L.push(`  ${e.code}: { http: ${e.http}, retryable: ${e.retryable} },`);
  }
  L.push("};");
  L.push("");

  const all = [...m.onDevice, ...[...m.namespaces.values()].flat(), ...m.onClient.filter((c) => !m.onDevice.includes(c))];
  for (const c of all) {
    if (hasOptions(c)) {
      const members = c.params
        .filter((p) => !p.required && p.name !== "path" && !(p.name === "value" && c.params.some((x) => x.name === "by")))
        .map((p) => ({ name: p.name, type: tsType(p.type, m, "param", p.enum), optional: true, doc: `${sentence(p.doc)}${p.hasDefault ? ` @default ${JSON.stringify(p.default)}` : ""}` }));
      if (c.takesWait) members.push({ name: "wait", type: "boolean", optional: true, doc: waitDoc(c, "ts") });
      L.push(tsInterface(tsOptionsName(c), null, members));
      L.push("");
    }
    if (c.kind === "fields") {
      const members = c.fields.map((f) => ({ name: f.name, type: tsType(f.type, m, "return"), optional: c.takesWait }));
      if (c.takesWait) members.push({ name: "accepted", type: "boolean", optional: true, doc: "Present instead of the other fields when the phone accepted a network-cutting call without wait." });
      L.push(tsInterface(tsResultName(c), null, members));
      L.push("");
    }
  }

  L.push("type Runner = (cmd: string, kind: ReturnKind, params: Params) => Promise<any>;");
  L.push("");
  for (const [ns, cmds] of m.namespaces) {
    L.push(`/** The ${ns}.* commands, reached as d.${ns}. */`);
    L.push(`export class ${pascal(ns)}Commands {`);
    L.push("  constructor(private readonly _run: Runner) {}");
    for (const c of cmds) {
      L.push("");
      L.push(tsMethods(c, "device", m).join("\n\n"));
    }
    L.push("}");
    L.push("");
  }

  L.push("/** Commands that run on one phone. Device extends this and implements the hooks. */");
  L.push("export abstract class DeviceCommands {");
  L.push("  protected abstract _run(cmd: string, kind: ReturnKind, params: Params): Promise<any>;");
  L.push("  protected abstract _saveImage(cmd: string, params: Params): Promise<any>;");
  L.push("  protected abstract _saveJson(cmd: string, params: Params): Promise<any>;");
  L.push("  protected abstract _runElement(cmd: string, kind: ReturnKind, params: Params): Promise<any>;");
  L.push("  protected abstract _loadImage(image: unknown): Promise<string>;");
  for (const ns of m.namespaces.keys()) {
    L.push("");
    L.push(`  get ${ns}(): ${pascal(ns)}Commands {`);
    L.push(`    return new ${pascal(ns)}Commands((cmd, kind, params) => this._run(cmd, kind, params));`);
    L.push("  }");
  }
  for (const c of m.onDevice) {
    L.push("");
    L.push(tsMethods(c, "device", m).join("\n\n"));
  }
  L.push("}");
  L.push("");

  L.push("/** Commands the PC server answers itself. Droidline extends this and implements _run. */");
  L.push("export abstract class ClientCommands extends EventEmitter {");
  L.push("  protected abstract _run(cmd: string, kind: ReturnKind, params: Params): Promise<any>;");
  for (const c of m.onClient) {
    L.push("");
    L.push(tsMethods(c, "client", m).join("\n\n"));
  }
  L.push("}");
  L.push("");
  return L.join("\n");
}

const CS_KEYWORDS = new Set([
  "abstract", "as", "base", "bool", "break", "byte", "case", "catch", "char", "checked", "class", "const",
  "continue", "decimal", "default", "delegate", "do", "double", "else", "enum", "event", "explicit", "extern",
  "false", "finally", "fixed", "float", "for", "foreach", "goto", "if", "implicit", "in", "int", "interface",
  "internal", "is", "lock", "long", "namespace", "new", "null", "object", "operator", "out", "override",
  "params", "private", "protected", "public", "readonly", "ref", "return", "sbyte", "sealed", "short",
  "sizeof", "stackalloc", "static", "string", "struct", "switch", "this", "throw", "true", "try", "typeof",
  "uint", "ulong", "unchecked", "unsafe", "ushort", "using", "virtual", "void", "volatile", "while",
]);
// Exceptions in namespaces C# files usually import; a generated class with one of these names gets a Droidline prefix.
const CS_TAKEN_EXCEPTIONS = new Set([
  "AccessViolationException", "AggregateException", "ArgumentException", "ArithmeticException",
  "DirectoryNotFoundException", "EndOfStreamException", "FileNotFoundException", "FormatException",
  "HttpRequestException", "IndexOutOfRangeException", "InvalidCastException", "InvalidOperationException",
  "IOException", "KeyNotFoundException", "NotImplementedException", "NotSupportedException",
  "NullReferenceException", "OperationCanceledException", "OutOfMemoryException", "OverflowException",
  "PathTooLongException", "PlatformNotSupportedException", "SocketException", "TaskCanceledException",
  "TimeoutException", "UnauthorizedAccessException",
]);
// Handwritten members of Device and DroidlineClient, including the hooks the generated methods call.
const CS_RESERVED = {
  device: [
    "CallAsync", "OnNotificationAsync", "ReleaseAsync", "DisposeAsync", "RunAsync", "RunValueAsync", "RunFieldsAsync",
    "RunElementAsync", "RunElementsAsync", "SaveImageAsync", "SaveJsonAsync", "Client", "Id", "LeaseId", "History",
    "Name", "Ttl", "Close", "Dispose",
  ],
  client: [
    "CallAsync", "LeaseAsync", "ReleaseAsync", "ConnectAsync", "DisposeAsync", "RunAsync", "RunValueAsync",
    "RunFieldsAsync", "Host", "Port", "Connected", "Device", "History", "On", "Off", "Close", "Dispose", "ProtocolVersion",
  ],
};
const CS_HANDWRITTEN_TYPES = new Set([
  "Device", "LeasedDevice", "DroidlineClient", "Element", "DroidlineObject", "DroidlineEvent", "DroidlineException",
  "ServerNotRunningException", "ConnectionLostException", "HistoryEntry", "ImageInput", "Testing", "Params", "Json",
  "Query", "ErrorCodes", "ErrorFactory",
]);
// Members of DroidlineObject, which every result and spec type extends.
const CS_OBJECT_MEMBERS = new Set([
  "Count", "Keys", "Values", "Item", "Get", "Has", "ToJson", "ContainsKey", "TryGetValue", "GetEnumerator",
  "Equals", "GetHashCode", "ToString", "GetType",
]);
const CS_LOCALS = new Set(["msg", "cancellationToken"]);
const CS_CANCEL_DOC = "Stops waiting for the reply. A command already sent may still run on the phone.";
const CS_QUERY_DOC =
  "A query object instead of a field and value: a Query, a dictionary, or an anonymous object whose property names " +
  'are the query keys as they are, such as new { textContains = "Wi", long_clickable = true }.';

const csIdent = (name) => {
  const c = camel(name);
  return CS_KEYWORDS.has(c) ? `@${c}` : c;
};
const csNullable = (t) => (t.endsWith("?") ? t : `${t}?`);
const csValueType = (t) => /^(int|double|bool)\??$/.test(t);
const xml = (s) => String(s).replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");

function csLiteral(v) {
  if (v === true) return "true";
  if (v === false) return "false";
  if (v === null) return "null";
  if (Array.isArray(v)) return `new[] { ${v.map(csLiteral).join(", ")} }`;
  return typeof v === "string" ? JSON.stringify(v) : String(v);
}

function csType(type, m, ctx) {
  if (type.union) {
    const rest = type.union.filter((t) => t.name !== "null");
    const t = rest.length === 1 ? csType(rest[0], m, ctx) : "object";
    return rest.length < type.union.length ? csNullable(t) : t;
  }
  if (type.list) {
    const inner = csType(type.list, m, ctx);
    return ctx === "param" ? `IEnumerable<${inner}>` : `IReadOnlyList<${inner}>`;
  }
  const map = {
    string: "string", int: "int", number: "double", bool: "bool", null: "object?", base64: "string",
    object: ctx === "param" ? "object" : "DroidlineObject", function: "Delegate",
    selector: "object", selector_pair: "object", step: "object", image: "ImageInput",
  };
  return map[type.name] ?? m.typeNames.get(type.name);
}

const csMethodName = (name) => `${pascal(name)}Async`;
const csResultName = (cmd) => `${pascal(cmd.name)}Result`;

// Turns the Python-flavoured spec example into C#: keyword args become named arguments, lists arrays,
// pairs value tuples, and a one-item tuple an object array.
function csExample(example, receiver) {
  const strings = [];
  const masked = example.replace(/"(?:[^"\\]|\\.)*"/g, (s) => {
    strings.push(s);
    return `\u0000${strings.length - 1}\u0000`;
  });
  const call = /^([A-Za-z_][\w.]*)\((.*)\)$/.exec(masked);
  if (!call) return null;
  const tokens = [];
  const re = /\s*(?:\u0000(\d+)\u0000|(-?\d+(?:\.\d+)?)|([A-Za-z_]\w*)|([()[\],=]))/y;
  const body = call[2];
  let pos = 0;
  while (pos < body.length && !/^\s*$/.test(body.slice(pos))) {
    re.lastIndex = pos;
    const t = re.exec(body);
    if (!t) return null;
    pos = re.lastIndex;
    if (t[1] !== undefined) tokens.push({ k: "lit", v: strings[Number(t[1])], str: true });
    else if (t[2] !== undefined) tokens.push({ k: "lit", v: t[2] });
    else if (t[3] !== undefined) tokens.push({ k: "id", v: t[3] });
    else tokens.push({ k: t[4] });
  }
  let i = 0;
  const take = (k) => {
    if (tokens[i]?.k !== k) throw new Error(`expected ${k}`);
    return tokens[i++];
  };
  const expr = () => {
    const t = tokens[i++];
    if (!t) throw new Error("unexpected end");
    if (t.k === "lit") return { code: t.v, str: t.str === true };
    if (t.k === "id") return { code: { True: "true", False: "false", None: "null" }[t.v] ?? t.v };
    if (t.k !== "[" && t.k !== "(") throw new Error(`unexpected ${t.k}`);
    const close = t.k === "[" ? "]" : ")";
    const items = [];
    let trailing = false;
    while (tokens[i]?.k !== close) {
      items.push(expr());
      trailing = tokens[i]?.k === ",";
      if (!trailing) break;
      i++;
    }
    take(close);
    const codes = items.map((x) => x.code).join(", ");
    if (t.k === "[") {
      if (!items.length) return { code: "new object[0]" };
      return { code: items.every((x) => x.str) ? `new[] { ${codes} }` : `new object[] { ${codes} }` };
    }
    if (items.length === 1) return trailing ? { code: `new object[] { ${codes} }` } : items[0];
    return { code: `(${codes})` };
  };
  const args = [];
  try {
    let named = false;
    while (i < tokens.length) {
      if (tokens[i].k === "id" && tokens[i + 1]?.k === "=") {
        const name = csIdent(tokens[i].v);
        i += 2;
        args.push(`${name}: ${expr().code}`);
        named = true;
      } else {
        if (named) return null;
        args.push(expr().code);
      }
      if (i < tokens.length) take(",");
    }
  } catch {
    return null;
  }
  const parts = call[1].split(".");
  const path = parts.map((s, k) => (k === parts.length - 1 ? csMethodName(s) : pascal(s))).join(".");
  const code = `await ${receiver}.${path}(${args.join(", ")});`;
  return code.replace(/\u0000(\d+)\u0000/g, (_, n) => strings[Number(n)]);
}

function csWaitDoc(cmd) {
  const method = csMethodName(cmd.name);
  let call = `a ${method} with a step that cuts the network`;
  if (cmd.cuts && cmd.params[0]?.name === cmd.cuts.param) call = `${method}(${csLiteral(cmd.cuts.when)})`;
  else if (cmd.cuts) call = `${method}(..., ${csIdent(cmd.cuts.param)}: ${csLiteral(cmd.cuts.when)})`;
  return (
    `Wait until the phone is back and return the final result. Without it, ${call} returns as soon as the phone ` +
    'accepts, with Accepted set, and the final result arrives later as a "result" event.'
  );
}

function csDocLines(doc, indent) {
  const L = [`${indent}/// <summary>${xml(doc.summary)}</summary>`];
  if (doc.remarks) L.push(`${indent}/// <remarks>${xml(doc.remarks)}</remarks>`);
  for (const p of doc.params ?? []) L.push(`${indent}/// <param name="${p.name.replace(/^@/, "")}">${xml(p.doc)}</param>`);
  if (doc.returns) L.push(`${indent}/// <returns>${xml(doc.returns)}</returns>`);
  for (const e of doc.exceptions ?? []) L.push(`${indent}/// <exception cref="${e.cref}">${xml(e.doc)}</exception>`);
  if (doc.example) L.push(`${indent}/// <example><code>${xml(doc.example)}</code></example>`);
  return L;
}

// The C# overloads of one method: commands with a selector get (string by, string value, ...) and (object query, ...).
function csVariants(meth, m) {
  const by = meth.params.find((p) => p.name === "by");
  if (meth.aliasBy) return [meth.params.map((p) => (p.name === "value" ? { ...p, doc: "The value to match" } : p))];
  if (selectorShape(meth) && by && typeIncludes(by.type, "selector")) {
    const forField = meth.params.map((p) => {
      if (p.name === "by") return { ...p, csType: "string", doc: `Which dump field to match: ${m.selectors.join(", ")}` };
      return p.name === "value" ? { ...p, required: true, doc: "The value to match" } : p;
    });
    const forQuery = meth.params
      .filter((p) => p.name !== "value")
      .map((p) => (p.name === "by" ? { ...p, csName: "query", csType: "object", doc: CS_QUERY_DOC } : p));
    return [forField, forQuery];
  }
  return [meth.params];
}

function csMethod(meth, owner, m, errorNames, indent, self) {
  const { cmd } = meth;
  const name = csMethodName(meth.method);
  const out = [];
  csVariants(meth, m).forEach((params, variant) => {
    const where = `command "${cmd.name}"`;
    const decl = [];
    const docs = [];
    let sawOptional = false;
    for (const p of params) {
      const ident = p.csName ?? csIdent(p.name);
      if (CS_LOCALS.has(ident)) fail(where, `param "${p.name}" clashes with a local of the C# method`);
      const type = p.csType ?? csType(p.type, m, "param");
      if (p.required && sawOptional) fail(where, `required param "${p.name}" follows an optional one in C#`);
      if (!p.required) sawOptional = true;
      decl.push(p.required ? `${type} ${ident}` : `${csNullable(type)} ${ident} = null`);
      docs.push({ name: ident, doc: `${sentence(p.doc)}${defaultNote(p, csLiteral)}`.trim() });
    }
    if (cmd.takesWait) {
      decl.push("bool? wait = null");
      docs.push({ name: "wait", doc: csWaitDoc(cmd) });
    }
    decl.push("CancellationToken cancellationToken = default");
    docs.push({ name: "cancellationToken", doc: CS_CANCEL_DOC });

    const sent = params.filter((p) => !p.clientOnly);
    const images = sent.filter((p) => p.type.name === "image");
    const body = [];
    body.push("var msg = new Params();");
    for (const p of sent.filter((x) => x.required)) {
      const ident = p.csName ?? csIdent(p.name);
      const value = p.type.name === "image" ? `await ${ident}.ToBase64Async(cancellationToken).ConfigureAwait(false)` : ident;
      body.push(`msg.Add(${JSON.stringify(p.name)}, ${value});`);
    }
    for (const p of sent.filter((x) => !x.required)) body.push(`msg.Opt(${JSON.stringify(p.name)}, ${csIdent(p.name)});`);
    if (cmd.takesWait) body.push('msg.Opt("wait", wait);');

    const wire = JSON.stringify(meth.wire);
    let ret = null;
    let call;
    let returns = null;
    if (cmd.save === "image") {
      ret = "byte[]";
      call = `SaveImageAsync(${wire}, path, msg, cancellationToken)`;
      returns = "The image bytes. They are also written to path when it is given.";
    } else if (cmd.save === "json") {
      ret = csResultName(cmd);
      call = `SaveJsonAsync<${ret}>(${wire}, path, msg, cancellationToken)`;
      returns = "The reply. It is also written to path as JSON when it is given.";
    } else if (cmd.wrap) {
      ret = cmd.valueType.list ? "IReadOnlyList<Element>" : "Element";
      call = `${cmd.valueType.list ? "RunElementsAsync" : "RunElementAsync"}(${wire}, msg, cancellationToken)`;
    } else if (cmd.kind === "value") {
      ret = csType(cmd.valueType, m, "return");
      call = `RunValueAsync<${ret}>(${wire}, msg, cancellationToken)`;
    } else if (cmd.kind === "fields") {
      ret = csResultName(cmd);
      call = `RunFieldsAsync<${ret}>(${wire}, msg, cancellationToken)`;
    } else {
      call = `RunAsync(${wire}, msg, cancellationToken)`;
    }
    const task = ret ? `Task<${ret}>` : "Task";

    let summary = cmd.summary;
    if (meth.aliasBy) summary = `${cmd.summary} Shorthand for ${csMethodName(cmd.name)}(${JSON.stringify(meth.aliasBy)}, value).`;
    let example = null;
    if (cmd.example && !meth.aliasBy && variant === 0) example = csExample(cmd.example, owner === "client" ? "client" : "d");
    const exceptions = cmd.errors.map((e) => ({ cref: errorNames.get(e.code), doc: e.doc }));
    out.push(...csDocLines({ summary, remarks: cmd.notes, params: docs, returns, exceptions, example }, indent));
    if (images.length) {
      out.push(`${indent}public async ${task} ${name}(${decl.join(", ")})`);
      out.push(`${indent}{`);
      for (const line of body) out.push(`${indent}    ${line}`);
      out.push(`${indent}    ${ret ? "return " : ""}await ${self}${call}.ConfigureAwait(false);`);
    } else {
      out.push(`${indent}public ${task} ${name}(${decl.join(", ")})`);
      out.push(`${indent}{`);
      for (const line of body) out.push(`${indent}    ${line}`);
      out.push(`${indent}    return ${self}${call};`);
    }
    out.push(`${indent}}`);
    out.push("");
  });
  return { name, lines: out };
}

function csObjectClass(name, summary, props, indent = "") {
  const L = [`${indent}/// <summary>${xml(summary)}</summary>`, `${indent}public sealed class ${name} : DroidlineObject`, `${indent}{`];
  props.forEach((p, k) => {
    if (CS_OBJECT_MEMBERS.has(p.name) || p.name === name) fail(`type "${name}"`, `property "${p.name}" clashes with a member of the class`);
    if (k) L.push("");
    L.push(`${indent}    /// <summary>${xml(p.doc)}</summary>`);
    L.push(`${indent}    public ${p.type} ${p.name} => ${p.getter};`);
  });
  L.push(`${indent}}`);
  return L;
}

function csGetter(type, field) {
  const key = JSON.stringify(field);
  if (type.endsWith("?")) return csValueType(type) ? `Get<${type}>(${key})` : `Get<${type.slice(0, -1)}>(${key})`;
  return csValueType(type) ? `Get<${type}>(${key})` : `Get<${type}>(${key})!`;
}

function renderCs(m) {
  const L = [];
  L.push(`// ${HEADER}`);
  L.push("#nullable enable");
  L.push("using System;");
  L.push("using System.Collections.Generic;");
  L.push("using System.Threading;");
  L.push("using System.Threading.Tasks;");
  L.push("");
  L.push("namespace Droidline;");
  L.push("");

  for (const t of m.types) {
    if (CS_HANDWRITTEN_TYPES.has(t.tName)) fail(`type "${t.name}"`, `"${t.tName}" clashes with a handwritten C# type`);
  }

  const csQueryType = { string: ["string?", "string"], bool: ["bool?", "bool?"], bounds: ["int[]?", "int[]"], query: ["Query?", "Query"] };
  L.push("/// <summary>A selector written as an object, passed in place of by and value. Every condition must hold on the same element.</summary>");
  L.push("public sealed partial class Query");
  L.push("{");
  m.queryKeys.forEach((k, n) => {
    const [type, read] = csQueryType[k.type];
    if (n) L.push("");
    if (k.doc) L.push(`    /// <summary>${xml(k.doc)}</summary>`);
    L.push(`    public ${type} ${pascal(k.key)}`);
    L.push("    {");
    L.push(`        get => Read<${read}>(${JSON.stringify(k.key)});`);
    L.push(`        set => Write(${JSON.stringify(k.key)}, value);`);
    L.push("    }");
  });
  L.push("}");
  L.push("");

  for (const t of m.types) {
    const props = t.fields.map((f) => ({
      name: pascal(f),
      type: "object?",
      getter: `Get<object>(${JSON.stringify(f)})`,
      doc: `The ${f} field as a plain value, or null when it is missing. Get<T>("${f}") converts it.`,
    }));
    L.push(...csObjectClass(t.tName, t.doc || `A ${t.name} object from the server.`, props));
    L.push("");
  }

  const fieldCommands = [...new Set([...m.onDevice, ...m.onClient, ...[...m.namespaces.values()].flat()])]
    .filter((c) => c.kind === "fields" && c.save !== "image");
  for (const c of fieldCommands) {
    const name = csResultName(c);
    if (CS_HANDWRITTEN_TYPES.has(name) || m.types.some((t) => t.tName === name)) fail(`command "${c.name}"`, `"${name}" clashes with another C# type`);
    const props = c.fields.map((f) => {
      let type = csType(f.type, m, "return");
      if (c.takesWait) type = csNullable(type);
      return { name: pascal(f.name), type, getter: csGetter(type, f.name), doc: `The ${f.name} field of the reply.` };
    });
    if (c.takesWait) {
      props.push({
        name: "Accepted",
        type: "bool",
        getter: 'Get<bool>("accepted")',
        doc: "True when the phone accepted a network-cutting call without wait; the other fields are then missing.",
      });
    }
    L.push(...csObjectClass(name, `The reply of ${c.name}.`, props));
    L.push("");
  }

  const errorNames = new Map();
  for (const e of m.errors) {
    let name = `${pascal(e.code.toLowerCase())}Exception`;
    if (CS_TAKEN_EXCEPTIONS.has(name)) name = `Droidline${name}`;
    if (CS_HANDWRITTEN_TYPES.has(name)) fail(`error "${e.code}"`, `"${name}" clashes with a handwritten C# type`);
    errorNames.set(e.code, name);
  }
  L.push("/// <summary>Error codes the server can answer with, from spec/commands.json.</summary>");
  L.push("public static partial class ErrorCodes");
  L.push("{");
  m.errors.forEach((e, n) => {
    if (n) L.push("");
    L.push(`    /// <summary>${xml(e.doc)}</summary>`);
    L.push(`    public const string ${pascal(e.code.toLowerCase())} = ${JSON.stringify(e.code)};`);
  });
  L.push("}");
  L.push("");
  for (const e of m.errors) {
    const name = errorNames.get(e.code);
    L.push(`/// <summary>${xml(e.doc)}</summary>`);
    L.push(`public sealed class ${name} : DroidlineException`);
    L.push("{");
    L.push(`    /// <summary>Creates the exception the SDK throws for ${e.code}.</summary>`);
    L.push("    /// <param name=\"message\">The server's message.</param>");
    L.push(`    /// <param name="retryable">Whether the call is safe to retry. Default: ${csLiteral(e.retryable)}.</param>`);
    L.push("    /// <param name=\"fields\">The extra fields the server sent.</param>");
    L.push(`    public ${name}(string message, bool retryable = ${csLiteral(e.retryable)}, DroidlineObject? fields = null)`);
    L.push(`        : base(message, ${JSON.stringify(e.code)}, retryable, fields, ${e.http})`);
    L.push("    {");
    L.push("    }");
    L.push("}");
    L.push("");
  }
  L.push("internal static class ErrorFactory");
  L.push("{");
  L.push("    internal static DroidlineException Create(string code, string message, bool? retryable, DroidlineObject fields)");
  L.push("    {");
  L.push("        switch (code)");
  L.push("        {");
  for (const e of m.errors) {
    L.push(`            case ${JSON.stringify(e.code)}:`);
    L.push(`                return new ${errorNames.get(e.code)}(message, retryable ?? ${csLiteral(e.retryable)}, fields);`);
  }
  L.push("            default:");
  L.push("                return new DroidlineException(message, code, retryable ?? false, fields);");
  L.push("        }");
  L.push("    }");
  L.push("}");
  L.push("");

  const checkNames = (names, owner, where) => {
    const taken = new Set();
    for (const n of names) {
      if (CS_RESERVED[owner].includes(n)) fail(where(n), `"${n}" clashes with a handwritten C# member`);
      if (taken.has(n)) fail(where(n), `"${n}" is generated twice on the C# ${owner} class`);
      taken.add(n);
    }
  };

  for (const [ns, cmds] of m.namespaces) {
    const cls = `${pascal(ns)}Commands`;
    if (CS_HANDWRITTEN_TYPES.has(cls)) fail(`namespace "${ns}"`, `"${cls}" clashes with a handwritten C# type`);
    L.push(`/// <summary>The ${ns}.* commands, reached as d.${pascal(ns)}.</summary>`);
    L.push(`public sealed class ${cls}`);
    L.push("{");
    L.push("    private readonly Device _device;");
    L.push("");
    L.push(`    internal ${cls}(Device device)`);
    L.push("    {");
    L.push("        _device = device;");
    L.push("    }");
    L.push("");
    for (const c of cmds) for (const meth of methodsOf(c)) L.push(...csMethod(meth, "device", m, errorNames, "    ", "_device.").lines);
    L.pop();
    L.push("}");
    L.push("");
  }

  const deviceNames = [];
  L.push("public partial class Device");
  L.push("{");
  for (const ns of m.namespaces.keys()) {
    deviceNames.push(pascal(ns));
    L.push(`    /// <summary>The ${ns}.* commands.</summary>`);
    L.push(`    public ${pascal(ns)}Commands ${pascal(ns)} => new ${pascal(ns)}Commands(this);`);
    L.push("");
  }
  for (const c of m.onDevice) {
    for (const meth of methodsOf(c)) {
      const { name, lines } = csMethod(meth, "device", m, errorNames, "    ", "");
      deviceNames.push(name);
      L.push(...lines);
    }
  }
  L.pop();
  L.push("}");
  L.push("");
  checkNames(deviceNames, "device", (n) => `C# Device member "${n}"`);

  const clientNames = [];
  L.push("public sealed partial class DroidlineClient");
  L.push("{");
  L.push("    /// <summary>The protocol version this SDK speaks.</summary>");
  L.push(`    public const int ProtocolVersion = ${m.proto};`);
  for (const c of m.onClient) {
    for (const meth of methodsOf(c)) {
      const { name, lines } = csMethod(meth, "client", m, errorNames, "    ", "");
      clientNames.push(name);
      L.push("");
      L.push(...lines.slice(0, -1));
    }
  }
  L.push("}");
  L.push("");
  checkNames(clientNames, "client", (n) => `C# DroidlineClient member "${n}"`);
  return L.join("\n");
}

function main() {
  const check = process.argv.includes("--check");
  let spec;
  try {
    spec = JSON.parse(readFileSync(SPEC_PATH, "utf8"));
  } catch (err) {
    console.error(`gen: cannot read ${relative(ROOT, SPEC_PATH)}: ${err.message}`);
    process.exit(1);
  }
  const model = loadModel(spec);
  const report = () => {
    if (!problems.length) return;
    console.error(`gen: spec/commands.json has ${problems.length} problem(s):`);
    for (const p of problems) console.error(`  - ${p}`);
    process.exit(1);
  };
  report();
  const outputs = [
    [OUT_PY, renderPython(model)],
    [OUT_TS, renderTs(model)],
    [OUT_CS, renderCs(model)],
  ];
  // The C# renderer finds name clashes only while it builds the file.
  report();
  let stale = 0;
  for (const [path, text] of outputs) {
    const rel = relative(ROOT, path).replace(/\\/g, "/");
    if (check) {
      const current = existsSync(path) ? readFileSync(path, "utf8").replace(/\r\n/g, "\n") : null;
      if (current !== text) {
        console.error(`gen: ${rel} is out of date. Run: node scripts/gen.mjs`);
        stale++;
      }
    } else {
      mkdirSync(dirname(path), { recursive: true });
      writeFileSync(path, text);
      console.log(`gen: wrote ${rel}`);
    }
  }
  if (stale) process.exit(1);
  if (check) console.log("gen: generated files are up to date");
}

main();
